March.
* _Start times up on New to > _3  and ~ 4 for Big,_
<<<<<<< HEAD
* _>>>Data keeps getting corrupted in the project dir<<<_
* Misc.
*** /snap/bin/emacs %F installed. Throws errors but is better than previous /usr/local/bin/emacs-30.2
Snap version is 31.0.50. not 30.2 
*** Focus follows mouse in Terminal:
defaults write com.apple.Terminal FocusFollowsMouse -string YES
** Vterm works and has correct $PATH.
** Rebuilt: Big failed after update. Reticulating Splines after restart. Could not clear it.
had to re-image the machine.
** Notes in the black book, including all software that needed install via brew.
** 560 natively compiles items in ~/.cache/emacs/eln-cache/
** Tried changing hl-line
Didn't work using: (set-face-background 'hl-line "Magenta")

Might try:

(use-package hl-line                                                                                                                                                                                                                                          :custom-face
  (hl-line ((t (:background "#FF00FF")))))

  Yeah, that didn't work either. Low priority, leave if for now.
  
** ODD thing, init.el.org had a missing '+' in one of the the #+begin_src emacs-lisp lines
this threw an error at the BOTTOM of the source block even though #+end_src was fine.
** Lisp projects go into ~/.quicklisp/local-projects/  +change that?+ _no_.
** Maze;
1. Turn right.
2. Can't turn right? Go forward.
3. Can't do 1or 2 turn left.

** "Debugging" David J. Agans
** Issue with id-locations - org roam. Fixed after org-id-update-id-locations run multiple times.
** recentf-save-list --> ~/.cache/emacs/var/recentf-save.el
** _init.el_ keeps getting corruped. Saved 12MAR_FREEZE.init.el to project dir.
** Tab function doesn't work in scratch buffer or org buffer. Also completions mess with Tab.
this is expected behavior save buffer as a program file (.lisp, .py, etc.) or enable text-mode.
** (let ((org-confirm-babel-evaluate nil)))  <-- should I toggle this customize then remove this line? NO
this is fine, just allows emacs to eval code blocks when tangling w/o user being prompted for each block.
** Completed Eglot With Rust to eliminate lsp-mode & lsp-ui ? <-- rust working well!
CLOSED: [2026-03-20 Fri 11:28]
** added defer to lsp-mode -- test this.
** Move load-path up from 589~ closer to top? Yes, done.
** Started misc-notes.org and copying everything from black notebook to org.
** Notes copied from paper to notebook.org
** COMPLETED On +Plucky+ - Make 3.14 Python the version that's used by system.
CLOSED: [2026-03-21 Sat 12:02]
** COMPLETED Friday 20MAR did +pip install 'python-lsp-server[all]'+nn
CLOSED: [2026-03-20 Fri 11:17]
Python *appears* to be working properly with completions, etc.

** COMPLETED 24MAR on +New+: made changed to section after line 426 - eglot. This affected Python, maybe?
CLOSED: [2026-03-25 Wed 09:14]
** there were dulicate lines. Removed them and re-organized through  to 499.
** had to revert to 20MAR _FREEZE.init.el
** COMPLETED org-lint threw error about headline in 3.org. Removed item, error disappeared, lost headline.
CLOSED: [2026-03-25 Wed 11:06]
** COMPLETED Added 'Issue' to list of otg todo keywords.
CLOSED: [2026-03-25 Wed 12:11]
** COMPLETED Yazi won't open pdf files. And opening files in emacs crashes emacs. cont,
CLOSED: [2026-03-26 Thu 08:44]
** Hitting o or <RET> on a text file opens it in emacs but that stops Yazi (not &). Once emacs quit Yazi resumes.
** COMPLETED slime-helper still an issue. Updated slime version then uncommented slime-helper line BUT
CLOSED: [2026-03-26 Thu 11:23]
emacs humg on load, again. Hard to comment out slime-helper line. This is *after* I re-installed slime-helper using ql in SBCL.
** Had to comment out slime-helper. Why?
** ISSUE Slime-helper appears to be gone from github. Forget about it/remove from init.el?
CLOSED: [2026-03-26 Thu 11:11]
** Removed slime-helper-master from elpa and then did (ql.... slime-helper didn't matter, won't load.
** aslo slime has to be updated by hand. Did this on all inits at work.

** ISSUE Tried adding code to disable flycheck in org-mode buffers but couldn't get it to work.
CLOSED: [2026-03-25 Wed 11:12]
** COMPLETED Commented out; paredit. Paredit probably not needed.
CLOSED: [2026-03-27 Fri 09:01]
** Is Paredit needed?
*
** NEXT Flycheck is global but;
** org-lint is enabled for org files
** COMPLETED lsp is enabled for Rust but clippy is not
CLOSED: [2026-03-27 Fri 09:14]
*** ISSUE rustic-clippy & cargo-clippy not enabled as checkers rust-clippy is /listed/ as checker, where is it?
** Solution was to run  +rustic-flycheck-setup+
** linters stil flakey for rust but syntax hiliting and completeion at point working.
** COMPLETED Had to sync 3.org on New with Plucky version.
CLOSED: [2026-03-30 Mon 08:56]
** COMPLETED tree-sitter now enabled on New and Big and init.el.org .
CLOSED: [2026-03-30 Mon 14:33]
** COMPLETED On New only (so far) ran profile-dotemacs.el - most time taken up by flycheck
CLOSED: [2026-03-31 Tue 12:38]
(which was loading EVERY language) and oddly erase-buffer. Removed a bunch of flycheck languages
and ;; out erase-buffer and load time for init.el went from 3.3/3.9 6o 3.1
** re-enabling flycheck-global-mode increased start time for init.el to 3.5/3.6 secs
but flycheck now enabled in python and common-lisp buffers as well as rust.
** Nothing to be done on Big or init.el.org since flycheck global wasn't changed there.
** COMPLETED Slime-helper is working on Big and New after deleted/reinstalled Slime, slime-helperon New.
CLOSED: [2026-03-31 Tue 10:56]
** current slime setup on init.el on Big and init.el.org (commented out on New):

 (add-to-list 'load-path "~/.emacs.d/elpa/slime-20260323.2010")
  (load (expand-file-name "~/.quicklisp/slime-helper.el")
  (setq inferior-lisp-program "/opt/homebrew/bin/sbcl")
  ;; (require 'slime-autoloads)
  ;; (eval-after-load "slime" '(progn (slime-setup '(slime-fancy))))
  
* COMPLETED Cleaned up init.el on New and init.el.org - Latest init is +01APR_FREEZE.init.el+
CLOSED: [2026-03-11 Wed 09:18]
** COMPLETED 31MAR On New and Big: no errors and native compile working.
CLOSED: [2026-03-31 Tue 09:25]
** COMPLETED Native compile working on Big & New.
CLOSED: [2026-03-30 Mon 08:56]
* COMPLETED  C-c r is now bound to recentf-save-list because list wasn't reliably updating on New.
CLOSED: [2026-03-27 Fri 08:35]
* COMPLETED LISP. Using (ql:quickload "cl-project") then
CLOSED: [2026-03-20 Fri 11:15]
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:

drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:

(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.
* COMPLETED sbcl --script <filename.lisp> working correctly. _Note_: to quit slime: , quit (that's comma, quit).
CLOSED: [2026-03-31 Tue 10:58]
* WAITING Experiment more with dired.
* WAITING Look at journal or org-roam for ability to step back in time to see changes.
** Testing org roam daily.
** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
** Majpr feature of Roam is ability to x-linkg notes and a db so search is easier.
* NEXT installed emacs 30.2 on +Plucky+ via snap  . (/snap/bin/emacs %F) Works but:
** recompiled init.el then changed some items causing warning. Good now w/ no warnings.
** Had to remove all refs to treemacs and nerd-icons.
** other issues. Works for now w/ GUI and is in the Menu.
** Note: /usr/local/bin//emacs-30.2 throws treesit error. The snap verson /snap/bin/emacs %F doesn't.
** Snap 30.2 on +Plucky+  Can't byte compile 30.2 on Plucky.
* NEXT installed emacs 30.2 on +Ducky+ via Homebrew. Terminal only. Check if native compile works.
** WAITING Ducky /usr/bin is on emacs 28 so many packages don't work correctly.
** treemacs disabled. -- why?
** showfonts removed -- don't care.
** company and company-box -- need 30.2
** global-flycheck mode -- again, probably due to emacs version.
** ISSUE  -- dashboard complains about ansi.
CLOSED: [2026-04-01 Wed 12:15]
** ISSUE -- slime-asdf complains about second.
CLOSED: [2026-04-01 Wed 12:15]
* 
