* Natively compiled files are in ~/.cache/emacs/eln-cache/30.2
* tree-sitter .dylib files are in ~.,cache/emacs/tree-sitter
* ~/.pyenv/shims/python3 is an alias to ~/opt/homebrew/lib/pyton3
* Note: Vertico supplies minibuffer completions. Corfu supplies in buffer completions via pop-ups. Company is in buffer completions.
* Note: eglot is lighter weight alternative to lsp-mode. Choose one, not both.bat no
* Reminder: C-c, C-v, C-t is Tangle.
* Reminder: C-a, C-k kill entire line. C-S, <bksp> does same thing.
* Reminder: C-, C-h, i open an info file.
C-x # close frame
* M-x checkdoc-minor-mode (turn on or OFF)
60 characters for docstrings
;;; Top is name and short description
;;; Commentary
;;; Code

*  Re-enabling pylsp in init.el (22OCT) restored marginalia, syntax highlithging, etc.
also no rpc issue.

C-x, r, w Register window
C-x, r, j jump back to registered window.

//opt/homebrew/share/emacs//site-lisp/

* fd command:
fd <-- will do a recursize search.

find ~/ -type f -name ** -size +1G

fd '.*s3$' <-- and file with 's' in second to last place.

fd profile //etc//  <-- search for profile in Dir /etc

fd . //src//  <-- show all files in /src

fd -e md <-- show files w/ extension md

fd -e js app <-- show files named app w/ js extension.

fd -g libc.so /usr <-- g is glob tag, search for exact name.

fd -H pre-commit <-- show Hidden files.

fd -I abbrev <-- show git files that would normally be ignored.

https://www.geeksforgeeks.org/linux-unix/fd-simple-and-fast-alternative-to-the-find-command/
