* Bookmarks
C-x r m ret set bookmark at point
C-x r m <bookmark name> ret (set name bookmark at point)
C-x r b <bookmark name> jump to named bookmark
C-x r l list all bookmarks
M-x bookmarks-save
M-x bookmakr-del ret <bookmark name> ret

* Brew
pyenv-sync
rbenv-sync
setup-ruby
* Building emacs from scratch
sudo apt install git build-essentials automake
sudo apt build-dep emacs
git clone https://git.savannah.gnu.org/git/emacs.git
./autogen.sh
./configure
make
unset emacs-load-path

OR

git clone   git://git.su.gnu.org/emacs.git
cd emacs
sudo apt-install build-essential
-- with tree-sitter
--without pip
make -j 3 (nproc)
src / emacs -q

* Comments
init files with outline-minor-mode can combine with org mode.
(load-custom-file ; <filename> )  one ; is inline comment
;;; outline heading level 1 (four ; is level 2, five is level 3, etc.)
M-x outline-minor-mode
M-x outline-demote
M-x outline-promote
M-x consult-outline  <-- jump to top level entries - those with ;;;
* Consult
C-x b is remapped to consult-buffer
C-x r b remapped to consult-bookmarks
C-x p b remapped to consult-project-buffer

* Denote
C-c n f consult denote find
C-c n g consult denote grep
C-c C-k org-kill-note-or-show-branches
(Abort triggers dieriectory does not exist create? (y/n) dialog.
* Dired
M-p or M-n to cycle prev, next buffer
M-del to clear
~/ to delete (not shadow) previous path
in Dired;
o to open file
C-x 0 to close
C to copy
R to rename
D to delete
up is back
m/u mark/unmark
U unmark all
X to execute
C-x, C-u toggle editable/read only C-c. C-c to commit
%-m mark files (regexp)
M odify permissions +x, +w, +r
M-x Project-find-file
    C-x p f
M-x consult-find
    #<item>#
C-x, C-f M-n <ret>
     (is Prot's find)
C-c d then @ to use same buffer.

* emacs client
emacsclient -e "sexexp"
emacsclient -c -editemacs --daemon
M-x server-start
M-:   "      "
M-x server-force-shutdown

C-u, C-x, C-c kill emacs server
C-x 5 0 cose frame
v, x, c (kill emacs, save buffers)

* Eval expression
C-x, e
C-M, x
Alt, n
C-u, n
M, n

* find


Find <path> expression options, tests, actions
-maxdepth (option)
-name, -type, size (test)
-print, exec (action)

example find . -type d   <-- show dirs only

find . -name "*.txt" -exec mv {} /path/to/new/directory \;

find . -siaze +100M -mtime -7

find . -type f -iname "**foobar**"  <-- case insensitive (vs. name, which IS case sensitive)

note: du is recursive find is not

df | grep file

alias ff''=du -a ~/project/ | grep -i $!'

alias ff='du -a ~/project/ 2>/dev/null |grep -i $1'

* Finding large files
find . -type f -exec ls -sh {} + | sort -rh | head -n 10

find ~ -type f -size +1G

find . -type f -exec ls -lh {} + | sort -rh -k 5 | head -n 10

* fzf
C-t search files and directories
C-r search command history
M-c chage current directory
* git
M-x git-status (or C-x g)
* Grep
grep default
grep --color-auto -nH --null -e' + "pattern"
instead:
(setopt grep-command "grep --color=auto -rni -A1"
lgrep search current directory - NOT recursive.
rgrep recursive search.
Zrgrep search compressed files.
find-grep every file in directory tree.
vc-git-grep runs git-grep.
counsel-grep search current buffer.
find-grep-dired find file name display in buffer.
find-name-dired similar to above.
kill-grep kill running grep processes.

* Info Mode
How an info file C-c C-h i
q= exit
H - list all commands
d return here
h = 1st time
Right-click will select item
n - next
p = previous
<SPACE> = forward at end of node to next node
<DEL> or <BKSPC> = back<--delete at beginning of node moves to previous node
PgUP and PgDOWN work as normal
C-l clear screen
b = beginning
? = help H in standalone reader, x to get back in stand alone reader
M-x visible-mode
] go to next node
[ go to previous node
m = go to subnode
u = up from submenu
<TAB> next subtopic
<UpARROW> <TAB Previous subtopic
i = search info
l = list, goes through history
r is opposite
L  creates node w/ history
d directory (shows all info nodes)
t = top of manual
click cross references to go there, l to return
f = specify cross  referene <RET>
f ? show all cross references for current node

* isearch
C-s C-r are forward, back.
M-e edit search.
<RET> stop@found item.
M-b stop@previous word.
M-m beginning of line.
M-e e.o.l.

C-s, C-s search again.
C-r, C-r    "           "   reverse.
M-M s Regexp search.
C-M-r  Regexp search, reverse.

C-M-s repeat last regexp search.
C-M-r       "               "           "   reverse.

M-x occur regexp standalone buffer.

M-s o send isearch to occur.

M-% query and replace
-y to replace one by one.
-! to replace all.
M-n or M-p to cycle replace.
M-s h hilite can change color and can canel.

* ls command (and aliases)
alias lb='cd ..'
alias lf='colorls -lath'
alias lg='colorls --gs'
alias ll='colorls -loa --sd'
alias lz='eza -la  --time=modified --color=always --icons=always'
alias ly='eza -lha --color=always --icons=always --group-directories-first'
alias lx='eza -la --time=created --color=always --icons=always --group-directories-first'

alias myip="curl http://ipecho.net/plain; echo"
alias bu='emacs -q -l ~/project/Prot/init.el &'
alias ec='emacsclient -n $1'
alias ez="emacsclient --create-frame $1"0

* Misc
C-u C-x C-c kill emacs, save buffer
C-c j journal jj
C-c, c, jj then C-x, C-s, and C-c, C-c 
C-x p projectile mode map
C-M, i compile at point
C-c, c capture
C-c a agenda
C-c l lsp-mode
C-x, C-j dired jump (jump to directory file is in)
C-x, C-r open recent
C-c, C-_ cycle mark ring
C-h, m describe commands for current mode.

* Movement
M-r Top, Center, Bottom (vs. C-l)
M-m 1st char of lin 0 ignores tabs and spaces at beginning of line.
C-M-p C-M-n next/last function
C-M-u C-M-d next/last function
M-d kill word (M-- M-d is kill word backwards)
C-- is same as M--
C-M-k kill sexp
C-<bkspc> delete backwards
M-\ delete whitespace
M-q fill paragraph
C-x h hilite whole buffer
M-z zap to charC-x, C-0 remove blank lines.
C-x, z repeat complex command.
* Org Mode
Shift-tab rotate status
C-c, C-t    "      "
C-ret create new item
M-ret under same level
M-up/down move item
C-c C-n next headline
C-c C-p previous headline
C-c C-j search for headline then C-s to find next match.
C-c, C-l insert link
C-c, C-o open link at point
 | table
M-ret list
-[] checklist
C-, C-x C-b to check box
C-, C-t to cycle TODO
Tab headline to lower level
Shift + up/down to change priority
C-c, C-q set tag
C-c, C-, then l for lisp (is org-insert-structure-template)
C-c, C-o open link in org-mode
C-c, <RET>  same.
C-c, C-l org insert link then file:
or
C-u, C-c, C-l is type file by default
C-c n a org-roam-alias-add
C-c n o  promote org heading to a node.
C-c n t add tag
C-c, C-c add tag to heading
C-c n i insert link
C-c n l lists all l iks to current bufferC-c & go back from link

C-c n d n daily

C-c, c is capture then t = todo and j = journal

S-b denote

C-c n f roam


----
* Org Roam
C-c n d n  new org roam daily
C-c n d Y  create a daily for Yesterday
C-c n d T  create a daily for Tomorrow
C-c n d y  view daily for Yesterday
C-d n d t   view daily for tomorrow
C-c n d b  view previous entry
C-c n d f   view next entry

C-c n l org roam buffer toggle
C-c n f org roam node find
C-c n i org roam node insert

C-M-i completion at point

C-c n d completion at point
C-c c org capture
C-c a agenda
C-c l org-store-ink
C-c C-l org-insert-link

* Organizing init file
;; comment
; inline notation
;;; outline heading level 1
;;;; outline heading level 2
M-x outline minor mode
M-x consult-outline
C-c C-,  insert code block

* Project.el
C-x p select project
C-x p f open file in project's dir.
C-x p b switch buffers in project's dir.
C-x p k kill all    "           "    "           "
M-x project-remember-projects-under   adds all projects in tnis buffer
C-c p g regex search the project
C-x p r replace text in project
C-x g magit
C-x p s shell
C-x p p project switch project
C-x p b switch to other buffer for this project
* Python
Using PIP & venv;
mkdir <dir name>
cd <dir name>
Python3 -m venv .venv
source .venv/bin/activate
pip install <dir name>
touch main.py
pip freeze requirements.txt    <-- good to know.
* Regexp
in lisp need \\ to escap a character.
interactive (isearch, etc.) only needs one \
~  $  ^  .  *  +  ?  [  \  -
] if it ends an alternative special.
\  escaped so special.
. matches any character except newline.
 * matches precedding char zero or more times.
+ one or more times. (* matches 0 or more).
? once or not at all.
 *? +? ??
 ^ beginning of line.
 ? end of line.
 [charset]
 ^ any char's those in set.
alt-s, o list lines matching regexp

* Replace : with newline:
M-x replace-string <RET> : C-q C-j
* Ruff
ruff check
ruff  check --fix
ruff format
ruff check --watch
( commented out pylsp when adding ruff. may need to pus pyslp back in.)

* Searching
C-s, C-w search for word at point
C-s, C-M-y search for charactoers at point
C-s, M-s, C-e search for whole lines at point
M-% search and replace
M-s, M-> show previous search

* Selection
C-spc set mark
C-x, C-x exchange point and mark
C-u, C-spc jump to prvious mark
save-excursion saves the location of point moves cursor bak there after a function is evaluated.

* Shell
type -a bash will show all installed versions.
#!/usr/bin/env -
\<shellcommand> will diable any alias
column -f -s <file.cvs) whre -f is number of fields and -s is delimiter.
fuser - list pid of all processes that have open files.
pid of
mkdir -p parent/child1,child2,child3, {grand kids}.

* Smart-Parens
M-x sp-cheat-sheet.

 | R W X |
 | 4 2 1 |

* Sorting
C-M-@ sortM-<#>
C-u <#> sort by field
C-u sort last field
C-xes repeat last command

* Tangle
C-c, C-v, C-t tangle
C-c, C-v, t   tangle
C-c, C-, |  source block lisp
M-x org-denote-block (C-c, C-d, d) also (C-c, C-v, C-c)
#+startup: content indent 
#+property: header-rogs :tangle "init.el"

* Testing changes to init.el

emacs -batch -l ~/.emacs.d/init.el --eval '(message "init.el loaded successfully")'

* Text commands
C-x <TAB> then <-- or --> change indent on selected region.
M-x replace-string ret : ret C-q, C-j ret (replace : with newline).
M-x sort-lines
M-y cycle kill ring
C-x, C-i or C-x tab indent
C-M-@ sort lines
Cu, C-spc prev mark
M-y cycle kill ring
M-shit-2 move mark forward one word
M-@ move selection <--> one word
C-x, C-p seect whole buffer
C-v, C-_ move point to previous mark
C-x, C-x swap mark and point
C-x, esc repeat last command
C-d, M-d delete fwd/delete back
C-M k kill sexexp
C-bkspc kill word backwards
M-\ delete whitespace
M-i insert whitespace
M-c join previous line
C-c, C-; comment
C-x z repeat complex command
M-q fill paragraph
M-} select whole paragraph
C-w kill selected reqion
M-w copy selected region
C-x, C-spc pop global makr ring
C-u, C-j just to last mark in ring
C-u, C-spc pop last mark off ring
M-h select bock
M-c, \   format region
M-^ join prvious line
M- \ delete whitespace
M-i insert whitespace
C-<BKSPC> kill <--
M-<SPC> only 1 space between chars.
M-c, M-v, M-l Caps, upcase, lowercase
C-x, C-, comment our current line
C-M-\ re-indent region
M-q fill paragraph
M-d delete word M--, M-d delete word <--
C-M-k kill sexpresion at point
M- l lowercase selected region
M-u uppercase     "           "
M-c initial Caps
M-e end of sentence.
M-z delete up to, and including a character.
C-spc set mark
C-x, C-x exchange pint and mark
C-u, C-spc jump to previous marks

* Use-package
:demand t <-- load immediately at startup (useful for completion frameworks).
:defer <-- load after startup.
:hook <-- load when hook invoked.
:mode <-- load when file will extension is opened.
:after <-- after other, specified, pasckages loaded.

* UV
uv init <new dir>
cd <new dir>
or
cd <existing dir>
uv init

options;  --app    --lib (build python packages)
uv init produces:

my-app
|- .python-version
|- README.md
|- main.py
|_ pyproject.toml
* Windows
C-x 2 horizontal split
C-x 3 vertical split
C-x + balance

* Yazi
 up/down or j/k to move
 <- -> or hl to move to child/parent
 move to top gg
 move to bottom G
 z zoxide jump
 Z zoxide and reveal file.
 o or enter to open a file
 tab to show file info
 y copy selected files
 x cut selected files
 p paste selected files
 d trash selected files
 D delete selected files
 r rename file
 spc  toggle selection of file
 esc cancel selection
 a create a file (or a dir if name ends in /)
 P same but overwrite
X Y cancel operation

* ZSHELL STUFF
C-t is fzf search files and directories
C-r is command history
M-c change current directory
--
Super, k is same as C-l or clear

