#!/bin/zsh
socket_file=$(~/bin/emacsserver)
emacs=/Applications/Emacs.app/Contents/MacOS/Emacs
emacsclient=/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_11/emacsclient

if [[ $socket_file == "" ]]; then
echo "starting Emacs server..."
$emacs --chdir $PWD --execute "(server-start)" $@ &
else
$emacsclient -n $@ --socket-name $socket_file
fi