;;; +July.+
#+PROPERTY: folded
* Start times down on New and Big to ~ 2 on New after fixing flymake-ruff.
** Start times up due to global-flycheck-mode - 16% of total startup time.
** ISSUE After flymake-ruff added start time went from < 1 to > 2 secs on New.
CLOSED: [2026-06-08 Mon 11:01]
* +Latest+ 24JUN.New.init.el w/ 23JUN_Big.init.el & 26MAY.zshrc
* COMPLETED Created ~/project/Prot/straight_prot.el as backup in case init.el blows up.
CLOSED: [2026-06-09 Tue 11:17]
this is the straight version of ~/project/Prot/init.el and works.
** ISSUE Make org mode files look nicer.
CLOSED: [2026-06-10 Wed 13:28]
** DONE Could not find theme better than sanity-tomorrow-eighties.
CLOSED: [2026-06-10 Wed 13:20]
** C-c, C-d is bound to org-deadline in org files.
Heldful at point in other docs.
** COMPLETED Installed uv on Big (was already on New).
CLOSED: [2026-06-15 Mon 08:36]
* COMPLETED Completion-Preview mode mode is now built in to emacs.
CLOSED: [2026-06-15 Mon 09:32]
bind a key for it?
<TAB> to accept M-i to complete up to longest common prefix.
M-x completion-preview-next-candidate cycles fwd
 M-x completion-preview-prev-candidate cycles back
* COMPLETED Quickproject works but need to create a dir and cd to it 1st.
CLOSED: [2026-06-24 Wed 13:28]
** example: in ~/project/lisp/ mkdir foobar cd foobar THEN run (quickproject:make-project "foobar")
*** ISSUE LISP projects.
** COMPLETED cl-project does not work or is not installed/configured correctly.
CLOSED: [2026-06-24 Wed 13:42]
(ql:quickload "cl-project") then
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:
drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:
                                        
(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.

 Lisp and elisp

** cl-project throws errors. Use quickproject for now?
*** throws an HTTPS statuse error 
*** (cl-project:make-project #p"lib/cl-sample/")
* ISSUE ~/.emacs.d/straight/repos is a git dir on New, not on Big but...
CLOSED: [2026-06-26 Fri 11:22]
it's not synched and not found. Doesn't appear to affect function but weird.
* TODO Running lisp programs:
Create a file named hello (you can drop the .lisp extension) and add this:

#!/usr/bin/env -S sbcl --script
(require :uiop)
(format t "hello ~a!~&" (uiop:getenv "USER"))
Make the script executable (chmod +x hello) and run it:

$ ./hello
hello me!

-------

;; filename.lisp
;; note the --script switch, not needed for raw code? NOPE, _doesn't display either way._
(print "hello world")
And then we run this in the terminal:

$ sbcl --script filename.lisp
"hello world"
$
===========
--load
If you use --load, then it will evaluate everything in your file, and then drop you into an interactive prompt so that you can interact with your program:

So let’s say we have the following file:

;; filename.lisp
(defun sum (list)
  (if list (+ (car list) (sum (cdr list))) 0))
And we call --load in the terminal:

$ sbcl --load filename.lisp
#<some preamble about sbcl you can ignore>
** (sum '(1 2 3 4 5))
15
---------
clisp <filename> runs a lisp script.
clisp -repl <filename> runs a script then drops to the repl.
* Homogulated init.el on Big and New. New slower load than Big.
** Rainbow-delimiters installed by use-package on Big caused error
when doing straight-pull-all. Deleted the package then changed use package line in init:
(straight-use-package 'rainbow-delimiters)
load-time went down by over 1/2 second and no errors. Will see if straight-pull-all now goes without error.
