

January.
* _Start times from _~ 3.5, up from 3  on New,  and ~4 for Big,_
* TODO Native compile working on Big & New. Can't compile 30.2 on Plucky.
* On +Plucky+, terminal mode emacs doesn't give treesit error but graphical launch does. _investigate_
* COMPLETED Is pyvenv useful? It's on Big, not on New.
CLOSED: [2026-01-06 Tue 09:58]
* COMPLETED Tweaked ~/project/Prot/init.el to remove uneeded items.
CLOSED: [2026-01-05 Mon 12:51]
original saved in Prot folder as init.el.backup and init.el.original
* COMPLETED Tree-sitter was running globaly - even on org files so modified it on New, Big, init.el.org.
CLOSED: [2026-01-05 Mon 13:35]

(require 'tree-sitter)
(require 'tree-sitter-langs)
(add-hook 'rust-mode-hook #'tree-sitter-mode)     _<-- added_
(add-hook 'python-mode-hook #'tree-sitter-mode) _<-- added_

;; (global-tree-sitter-mode)  _<-- commented out_

;; (use-package rust-mode
;;   :init
;;   (setq rust-mode-treesitter-derive t))
;; ;; or just for rust-mode
;; ;; (add-hook 'rust-mode-hook #'tree-sitter-mode) +was same on 18AUG+
;; ;; Load the language definition for Rust, if it hasn't been loaded.
;; ;; Return the language object.
;; (tree-sitter-require 'rust)
;; (tree-sitter-require 'python)
;; (global-tree-sitter-mode)  _<-- not this_
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode) _<-- same before (18AUG) and now (05Jan)_
* COMPLETED Lexical scoping on New, Big and init.el.org.
CLOSED: [2026-01-05 Mon 13:39]
* COMPLETED Friday 12DEC.  - Enabled flycheck in New, Big and init.el.org (w/o Elpy):
CLOSED: [2025-12-12 Fri 13:49]

(use-package flycheck
  :ensure t
  :config
  (add-hook 'after-init-hook #'global-flycheck-mode))
**  NOTE: New, init.el.org, and Big have simplifed Flycheck (w/o Elpy).
* COMPLETED Reconciled init.el on New with Big and init.el.org but now can't click on items in dashboard.
CLOSED: [2026-01-06 Tue 14:16]
** Had to copy Big's init.el to New to get back ability to click to open files in Dashboard.
Question is, now, has that messed anything else up? Rust, Python, lisp, etc. ? Will need to check.
*** New has 115 packages in elpa, with 95 loaded. Big has 105 packages with 88 loaded.
this is even though they now have the same init.el files.
elpa will  be bigger than laoded due to signed packages with sam names.
*** Python working on New after swapping Big's init.el to it to fix can't click issue with Dashboard.
*** Rust Flycheck, eglot, and rust-analyzer working but no completion or marginalia that I can see.
* COMPLETED json errors. why? -- was eglot related (after-save-hook.)
CLOSED: [2026-01-07 Wed 11:13]
** note: the below line is a dupe of <-- 519.
(setq-local lsp-inlay-hint-enable t)   <-- 533
** ruby-lsp not installed. used brew install ruby-lsp on new and big also ruff install on big.
**  On New: commenting out lines 449-450 resolved the json-rpc error.
(with-eval-after-load 'eglot
(add-hook 'after-save-hook 'eglot-format))
* COMPLETED init.el on New and Big, init.el.org and 07JAN_New_init.el all upda to date. _FREEZE!_
CLOSED: [2026-01-08 Thu 08:58]
** WAITING Rust-analyzer is working but needs more testing.
** NEXT Still having issue discovering workspace (rust). Look into this.
*** commenting out all lines about hints stopped hints error.
*** running M-x lsp-workspace-folders-remove then Mx lspt-workspace-folders-add did not fix issue.
added the specific fold -->  ~/project/rust/hello_rust/  to folders did not fix Failed to load workspce.
** I wonder if a toml file in the root of the project is needed?
see https://github.com/emacs-rustic/rustic/issues/110 for a discussion on finding project root and workspace.
* COMPLETED Flycheck now working with elisp files on New & Big.
CLOSED: [2026-01-07 Wed 14:56]
** Flycheck; C-c ! v to verify setup, C-c ! n (next), C-c ! p (prev), C-c ! | (all), C-c ! e (explain).
*** No idea why it started working. Could diff older init.el files to see what changed.
*** Had to mess around with init.el after flycheck flagged lots of errors.
* COMPLETED Yazi stopped showing previews. Removed yazi.toml from  ~/.config/
CLOSED: [2026-01-12 Mon 11:09]
and did brew reinstall yazi. This restored preview. No idea is anything was lost by removing yazi.toml
** had to add a new yazi-default.toml and edit it to get show hidden and correct spacing (1, 4, 3).
** Big and New using catppuccin.mocha.
* COMPLETED Updated Ruby to 4.0.0 had to pip install colorls after. Also had to edit path in .zshrc
CLOSED: [2026-01-13 Tue 09:20]
* COMPLETED 14JAN - init.el same on New, Big and init.el.org
CLOSED: [2026-01-14 Wed 13:13]
* COMPLETED Cleaned up an tested aliases in .zshrc on New and Big.
CLOSED: [2026-01-15 Thu 11:11]
** COMPLETED Changed lx command alias in .zshrc so it shows time=modified instead of created:
CLOSED: [2026-01-15 Thu 10:31]
alias lx='eza -la --time=modified --color=always --icons=always --group-directories-first'
* WAITING Eglot fails to discover rust or python workspaces.
** Python is working w/ syntax, Marginalia, etc.
** Rust - load cargo file 1st then src file and lsp will connect without complaining. _<-- not any longer!_
* WAITING At this point I'm considering putting Rust aside and focusing on Python.

* NEXT Eglot couldn't determine lsp-server on Big even though it says emacs-lisp.
** lisp on New is odd. Slime is enabled, but Compay wants a language server (for eglot?).
*** Flycheck does appear to be working in lisp buffers on New and Big.
isp should NOT require a language server but eglot should work with lsp-mode.
*** copied init.el from New to Big, still not checking. Does Flycheck on Big need to know what the checker is?
No, seems to know it's emacs-lisp.  C-c ! v shows everything looks o.k. on both machines.
** in Terminal: cargo locate-project --workspace --message-format plain to find Cargo.toml
