;;; +June.+
* Start times down on New and Big to < 2 with Straight and Plucky.
** 71 (New) 67 (Big) packages loaded in Straight vs. 93 in package-based init.
78 packages in New's repo, 63 in Big's repo (less than installed!)
** Be sure 2 use (straight-use-package '<package> but (use-package <package>)
or emacs won't install/use the package.
* WAITING LISP. Using (ql:quickload "cl-project") then
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:

drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:
                                        
(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.
* Misc
** COMPLETED  C-c r is now bound to recentf-save-list because list wasn't reliably updating on New.
CLOSED: [2026-03-27 Fri 08:35]
** COMPLETED Look at journal or org-roam for ability to step back in time to see changes.
CLOSED: [2026-04-13 Mon 09:41]
*** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
*** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
*** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
*** Majpr feature of Roam is ability to x-linkg notes and a db so search is easier.
** use-package infers :defer t so package does not load immediately.
*** with straight can use :straight t
** _Note:_ did NOT change require statements that looked like part of fuctions (not sepearte on own line).
*** COMPLETED Tried to install an info item.
CLOSED: [2026-04-29 Wed 12:58]
*** Secret was to add /opt/homebrew/share/info/ to info-additional-directory-list.
install-info --info-dir=/opt/homebrew/share/info ~/Software/muse.info
*** Tried adding /opt/homebrew/share/info to info-default-directory-list but it did not transfer to info-directory-list.
*** doing:   !%/opt/homebrew/opt/texinfo/bin!/info!%   gave texinfo display, including muse.info so...
*** muse.info probably not showing up in emacs because it was a texinfo file, not an info file.
*** comaprison of texinfo Top Directory and emacs info Top Directory proves they are pulling from two different places.
 the texinfo stuff seems to be the standard GNU stuff that should be in info. The stuff in emacs appears to be odd-ducks.
** re-installed homebrew emacs, deleted alias in .zshrc and linked brew emacs to emacs in .zshrc
CLOSED: [2026-05-05 Tue 09:33]
* So... moved ~/.emacs.d/elpa to ~/back_elpa/ then installed Straight Bootstrap.
*** removed all mention of package from init.el
*** lot of work to replace require with use-package commented out a lot of stuff to get a working init.
** More work stil to be done. Left eglot intact but killed all lsp-mode stuff and a lot of Rust stuff.
*** quicklisp/slime-helper loaded.
*** both big and new have rainbow-delimiters in straight/repos but init.el complains.
** COMPLETED Both New and Big working w/ straight version of init.el
*** DONE New & Big moved to straight. Don't change init.el.org needed for Plucky & Ducky.
CLOSED: [2026-05-15 Fri 11:02]
* .zshrc path checked on New and Big and a copy sent to ~/project/
* Rust, Rustic, lsp, lspUI, _tree-sitter_
* ISSUE +Python+-mode/eglot broken on New, but not on Big!
** running M-x eglot prompts for localtion of pylsp...
giving it /Users/charles.marano/.pyenv/shims/pylsp starts eglot and it seems to work.
** Internet says it's because emacs is using project.el not project.elc
** Rolling back init.el a week (17May) did not fix Python Problem on New.
** +Python+ on New - capf: HOMEBREW_NO_PATH_SHADOW_CHECK=1 in .zshrc to force emacs
to use homebrew pylsp instead of shims/pylsp. Big was using /opt/homebrew//bin/pylsp and working.
Which command in terminal still shows /Users/charles.marano/.pyenv/shims/pylsp which is odd.
** Python: when starting eglot have to tell emacs where pylsp is even though...
it's on the $PATH /Users/charles.marano/.pyenv/shims/pylsp
** json rpc message is from eglot - it can't find might be from closing progrs.
* _Lisp_ on New - can't complete capf not connected. But lisp on Big can.
is using company-dabbev-code company-gtags company-etags company-keywords.
** _Lisp_: Company: backend company-capf error "Not connected." with args (prefix)
** C-h v then company-backends shows no backends for lisp or elisp on New.
** capf for lisp IS working on Big. see capf_lisp.txt for more.
* You can force company to find dabbreve by using company-begin-backend
and then choosing the dabbrev backend from the list that appears in the minibuffer.
* Start using journal to organize thoughts.
* Comparing Elpa and Repos to see what's in the old init that's not in the new.
