* June
* Start times around 3 seconds.
** New taking 3+ seconds. Big now taking 9+ seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
* COMPLETED zoxide does work. Did cd ~/.emacs.d then cd ~/project after could do cd .emacs.d
CLOSED: [2025-06-09 Mon 10:27]
and cd project.
* COMPLETED emacs server / client.
CLOSED: [2025-05-22 Thu 07:42]
** put plist into launch agents folder to start emacs --daemon automatically on restart.
*** failed. using N-X server-start from emacs for now.
*** advantage is should be able to force files to open quickly in emacsclient.
*** emacs start ~3 secs. emacsclient starts in 2.37 secs. ec opens files instantly.
*** emacsclient -n <filename>  <-- reuse frame, seems to work.
*** emacsclient -a '' -c <--satarts daemon and client
*** emacs --daemon   emacs --fg-daemon emacsclient -cache
*** emacsclient --no-wait -r <filename>   <-- should reuse existing frame, doesn't.
*** emacsclient -cn <filename> &  <-- seems to work. For intial frame after emacs --daemon. _<--_
*** emacsclient --no-wait -c <filename> <-- new GUI frame. _<--works_
** Use C-x 5 0 to kill instance. _<-- works_
**  added alias to .zshrc -->   alias ec='emacsclient -n $1' +<-- use this.+
* COMPLETED Tried Aerospace tiling WM. It immediately bugged out so leave for later.
CLOSED: [2025-06-09 Mon 10:27]
* COMPLETED Put Emacs Elements Tangle notes in Project.
CLOSED: [2025-06-09 Mon 10:27]
** Tangled init.el.org and had lots of duplicate sections. Did tangle aadd to existing newest.el?
instead of replacing it? Will try tangling again later.
* DONE Trying Yasnippet again. Added code to init.el if successful add to
CLOSED: [2025-06-09 Mon 10:27]
init.el.org and tangle so resulting file can be put in projects dir for Big and Plucky (and Ducky?).
additions to init.el are from ln 191 to ln 196.
installed yas-snippets, which show up as elpy-20250404.2349 and have python snippets only.
this and .emacs.d/snippets are only yas-snippet-dirs
** got +some+ snippets in yasnippet-snippets-20250507.2002/snippets working.
had to change < to +  since auto parens screw them up. This is a problem as any changes
I make will be lost when the yasnippet-snippets packae is updated.
** Other snippets not working. 
+remove again?+
* Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* Lisp programming.
* Tried kitty terminal.  It may be faster, not sure.
** Forn default, too small, editor vi, etc. Edited ~/.config/kitty/kitty.conf
** added kitty-themes to .config/kitty. Chose MaterialDark.
** set up kitty on Big. Different themes on each. New = Materialdark. Big is Tomorrow_Night_Eighties.
** kitten choose-fonts doesn't apper to work, doesn't modify kitty.conf3
** It writes a separate Kitty fonts section at THE END of kitty.conf
*** worked AFTER I gave kitty full disk access in Privacy & Security.
*** Which is better? Materialdark or Tomorrow_Night_Eighties?
*** currently using Tomorrow. May change back to Material.
* Trying WezTerm and Ghostty.
** WezTerm uses Lua to config and isn't hard. Colors look okay. Muted vs. ITerm2.
** Ghostty is supposed to be zero config but I'd like two line prompt.
** is doing two line prompt but is throwing error in shell integration file.
error in /Applications//Ghostty.app//Contents/Resources/ghostty/shell-intergration/zsh//ghostty-integration line 317.
