January.
* _Start times from _< 4  on New,  and < 5 for Big,_
* COMPLETED Friday 12DEC.  - Enabled flycheck in New, Big and init.el.org (w/o Elpy):
CLOSED: [2025-12-12 Fri 13:49]

(use-package flycheck
  :ensure t
  :config
  (add-hook 'after-init-hook #'global-flycheck-mode))
**  NOTE: New, init.el.org, and Big have simplifed Flycheck (w/o Elpy).
* COMPLETED Eglot fails to discover rust or python workspaces.
CLOSED: [2025-12-19 Fri 08:54]
** Python is working w/ syntax, Marginalia, etc.
** Rust - load carog file 1st then src file and lsp will connect without complaining.
* TODO Native compile working on Big & New. Can't compile 30.2 on Plucky.
* WAITING Lexical scoping on New, Dynamic on Big.
* WAITING json errors. why? -- may be hint related.
** note: the below line is a dupe of <-- 519.
(setq-local lsp-inlay-hint-enable t)   <-- 533
** ruby-lsp not installed. used brew install ruby-lsp on new and big also ruff install on big.
* NEXT Flycheck now working with elisp files on New. not on Big.
** No idea why it started working. Could diff older init.el files to see what changed.
** Had to mess around with init.el after flycheck flagged lots of errors.
** Eglot couldn't determine lsp-server on Big even though it says emacs-lisp.
** copied init.el from New to Big, still not checking. Does Flycheck on Big need to know what the checker is?
No, seems to know it's emacs-lisp.  C-c ! v shows everything looks o.k. on both machines.
