April.
* _Start times up on New to > _3  and ~ 4 for Big,_
<<<<<<< HEAD
* _>>>Data keeps getting corrupted in the project dir<<<_
* COMPLETED Cleaned up init.el on New and init.el.org - Latest init is +01APR_FREEZE.init.el+
CLOSED: [2026-03-11 Wed 09:18]
** COMPLETED 31MAR On New and Big: no errors and native compile working.
CLOSED: [2026-03-31 Tue 09:25]
** COMPLETED Native compile working on Big & New.
CLOSED: [2026-03-30 Mon 08:56]
* COMPLETED  C-c r is now bound to recentf-save-list because list wasn't reliably updating on New.
CLOSED: [2026-03-27 Fri 08:35]
* COMPLETED LISP. Using (ql:quickload "cl-project") then
CLOSED: [2026-03-20 Fri 11:15]
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:

drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:

(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.
* COMPLETED sbcl --script <filename.lisp> working correctly. _Note_: to quit slime: , quit (that's comma, quit).
CLOSED: [2026-03-31 Tue 10:58]
* WAITING Experiment more with dired.
* WAITING Look at journal or org-roam for ability to step back in time to see changes.
** Testing org roam daily.
** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
** Majpr feature of Roam is ability to x-linkg notes and a db so search is easier.
* NEXT installed emacs 30.2 on +Plucky+ via snap  . (/snap/bin/emacs %F) Works but:
** recompiled init.el then changed some items causing warning. Good now w/ no warnings.
** Had to remove all refs to treemacs and nerd-icons.
** other issues. Works for now w/ GUI and is in the Menu.
** Note: /usr/local/bin//emacs-30.2 throws treesit error. The snap verson /snap/bin/emacs %F doesn't.
** Snap 30.2 on +Plucky+  Can't byte compile 30.2 on Plucky.
* NEXT installed emacs 30.2 on +Ducky+ via Homebrew. Terminal only. Check if native compile works.
** WAITING Ducky /usr/bin is on emacs 28 so many packages don't work correctly.
** treemacs disabled. -- why?
** showfonts removed -- don't care.
** company and company-box -- need 30.2
** global-flycheck mode -- again, probably due to emacs version.
** ISSUE  -- dashboard complains about ansi.
CLOSED: [2026-04-01 Wed 12:15]
** ISSUE -- slime-asdf complains about second.
CLOSED: [2026-04-01 Wed 12:15]
* Tried Prelude and it ruined emacs. Had to try to re-install packages that were deleted.
** Org not formatting properly, had to comment out rainbow delimeters, LOTS of issues.
