* August
* _Start times around 7 seconds_, up from 3. Around 8 seconds for Big.
** New taking 3+ seconds. Big now taking 8 seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
** TODO Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* August misc.
** COMPLETED Played around w/ Yazi flavors.
CLOSED: [2025-08-05 Tue 13:01]
** COMPLETED Reconciled ~/projects/init.el.org with current init.el on new.
CLOSED: [2025-08-06 Wed 10:37]
** COMPLETED Yazi is odd. 'r' for rename opens emacs and you change filename there.
CLOSED: [2025-08-08 Fri 08:08]
** you can't paste into folder, you need to enter the destination folder then paste with 'p' ('P' to overwrite).
** copy is 'y' and cut is 'x'. Trash a file is 'd' after you select the file with <spc> ('D' to delete instead of trash).
** <Return> opens the file so don't that when moving, copying, etc. (also 'O' and <shift-Return>
** <tab> to show file info.
** COMPLETED Git on Big no longer requires a token when pulling/pushing etc. No idea why.
CLOSED: [2025-08-14 Thu 14:41]
** COMPLETED Tried a temporaty init.el to pretify org mode. Big mess. Blew up init.el on New.
CLOSED: [2025-08-14 Thu 14:41]
** Had to copy init.el from Big to reconcile. Think it's okay now.
** COMPLETED Moved older inits to project/MyStuff/Shell/Older inits. Added init.el.freeze20AUG.
CLOSED: [2025-08-20 Wed 11:29]
** COMPLETED Test gh on Big to see if ssh key works there. Git push/pul w/o Token working now.
CLOSED: [2025-08-20 Wed 11:30]
** COMPLETED Have to kill emacs server then start new server before ec will work.
CLOSED: [2025-08-20 Wed 11:32]

** Added (server-start) to init.el  and can now use ec $1 to open files quickly.
** All terminal apps instantly launch a file in the GUI version of emacs that's already open.
when ec is used:      'emacsclient -n $1'
(that's if M-x server-start has been done and it's a fresh instance of the server.

** COMPLETED init.el on Big - vertico stopped working. Fix was to copy init.el from New.
CLOSED: [2025-08-21 Thu 13:50]
** COMPLETED Trying to figure out project root.
CLOSED: [2025-08-25 Mon 12:32]
from 
vlogize on YouTube. Automate Adding New Projects in Emacs with Projectile and Treemacs - https://www.youtube.com/watch?v=RoZGPRK9fyo

(defun add-or-switch-project-dwim (dir)
(interactive (list (read-directory-name "Add to known projects: ")))
(projectile-add-known-project dir)
(find-file dir)
(treemacs-add-and-display-current-project))

added projectile and treemacs[

(projectile-mode +1)
;; Recommended keymap prefix on macOS
(define-key projectile-mode-map (kbd "s-p") 'projectile-command-map)
;; Recommended keymap prefix on Windows/Linux
;; (define-key projectile-mode-map (kbd "C-c p") 'projectile-command-map)


(keymap-global-set "C-c p" 'add-or-switch-project-dwim) 

** COMPLETED Installed elpa items on New that Big had and visa-versa.
CLOSED: [2025-08-26 Tue 14:12]
** COMPLETED For now use New for programming don't update Big yet. <-- too late.
CLOSED: [2025-08-28 Thu 08:05]
** COMPLETED Need to check contents of Elpa vs selected-packages in init.el on both Big & New.
CLOSED: [2025-08-28 Thu 08:05]
** COMPLETED removed  items from elpa on big and new. Added some to selected, ditto.
CLOSED: [2025-08-28 Thu 08:06]
** COMPLETED Python working on New and Big as intended. shows completions and marginalia.
CLOSED: [2025-08-28 Thu 08:43]
** COMPLETED New shows marginalia when doing python, Big doesn't. Why?
CLOSED: [2025-08-28 Thu 09:08]
* COMPLETED added projectile and treemacs to init.el.org tangled successfully.
CLOSED: [2025-08-26 Tue 14:11]
* COMPLETED Removed Re-installed elpy. Uncommented elpy/flycheck code at bottom of init.el
CLOSED: [2025-08-25 Mon 12:32]
now Python code appears to be getting full language checking, linting, marginalia, etc.
* COMPLETED Removed yas-snippet packages from ~/.emacs.d/elpa
CLOSED: [2025-08-19 Tue 14:45]
issues with elpy package. had to comment out all references to it <-- temporary, investigate.
* COMPLETED Had to disable zscaler to get 15.6 update to install on New.
CLOSED: [2025-08-14 Thu 14:42]
** COMPLETED After above I updated init.el.org and tangled.
CLOSED: [2025-08-19 Tue 14:35]
newtest.el showed a number of items theat need to be adressed;
auto-compile version wrong (old) some items missing that are in New's init.el etc.
** COMPLETED all ls aliases NOT for eza fail with:
** updated gems via rbenv. Set rbenv global. updated color ls. set clocale.
CLOSED: [2025-08-19 Tue 14:42]
**  opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1421:in 'block in Gem::Specification#activate_dependencies': Could not find 'clocale' (~> 0) among 95 total gem(s) (Gem::MissingSpecError)Checked in 'GEM_PATH=/Users/charles.marano/.gem/ruby/3.4.0:/opt/homebrew/lib/ruby/gems/3.4.0:/opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/gems/3.4.0' at: /opt/homebrew/lib/ruby/gems/3.4.0/specifications/colorls-1.5.0.gemspec, execute `gem env` for more information
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1407:in 'Array#each'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1407:in 'Gem::Specification#activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1389:in 'Gem::Specification#activate'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:290:in 'block in Gem.activate_bin_path'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:289:in 'Thread::Mutex#synchronize'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:289:in 'Gem.activate_bin_path'
        from /opt/homebrew/lib/ruby/gems/3.4.0/bin//colorls:25:in '<main>'

** COMPLETED Big blew up with Vertico errors related to consult, etc.
CLOSED: [2025-08-19 Tue 14:34]
Tried a delete and re-install of GNU Emacs 30.2 for Mac. Did not fix the issue.
Tried pruning changes made this morning. Nope.
Tried copying a good init.el to Big, same vertico error:
Tried commenting out large portions of ORG section. Nope.
Tired deleting Emacs 30 .plist. Nope.
Whacked huge sections of init.el and that erased error.
----
Copied init.el from New to Big then *commented out Vertico and marginalia sections.*
Then removed -   pacakge-delete  - vertico ad marginalia.
No warnings and Org docs display correctly BUT no completion
** COMPLETED Changes to init.el on New and Big.
CLOSED: [2025-08-19 Tue 14:45]
Added below lines to init.el statup time went to 7+ seconds. 9 for Big.

** from Prot's big init?
line 319 (add-hook 'org-mode-hook 'visual-line-mode)

line 329 (setq org-hide-emphasis-markers t)

** C-x, C-f defaults to ~/
line 53 (setq file-name-shadow-properties '(invisible t))
            (file-name-shadow-mode)
*** I'd prefer a situaton where it stays in current dir until you type ~/.bashrc

***  see below. might not need this.

** typing deletes selection.
line 56 (delete-selection-mode 1)

* lisp programming.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.
$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject:
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
<<<<<<< HEAD
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
* Prot emacs runs as GUI on New, as terminal app on Big. Why?
*  Added recent changes to New's init.el to init.el.org
