* September.
* new.init.el is latest System Crafters init.el - just to see how it compares w/ mine.
it's okay but nothing special. Do like JetBrainsMono Nerd Font though.
* Prot emacs runs as GUI on New, as terminal app on Big. Why?
* _Start times around 6+ seconds_, up from 3. Around 9 seconds for Big.
** Why are start times going up? 
** adding back GC changes to init.el and early-init.el cut this to 5+ secs.
** synched init.el on Big and New.
** ran profile-dotemacs.el biggest  % of startup time was org-babel-do-load-languages.
*** commented out rust, eshell and ruby 
*** commented out vterm
*** removed a lot of packages from packages and commented out all rust items but startup times not really shorter
*** restored most itmes back to init.el** added gc change to early init and restore to normal gc to init.el
** commented out some items on New in init.el to see if they affected startup times. They didn't.
haven't un-commented them yet so init.el on New does NOT match the other init.el files on New and Plucky.
had to go back to a safety save after C-x, C-r stopped working after oave changes to init.el on New.
did not bother to troubleshoot yet. 
* NEXT Freeze init.el and work on other things.
<<<<<<< HEAD
* new.init.el is latest System Crafters init.el - just to see how it compares w/ mine.
it's okay but nothing special. Do like JetBrainsMono Nerd Font though.
* Ducky wants to compile vterm-module every time.
Check early.init - no byte compile and init.el
* What did I need from $Store? - shower curtain.
=======
>>>>>>> 3ee47d6 (Monday Morning.)
