* October.
* _Start times around 5 seconds, 8 for Big_, up from 3. 
* COMPLETED Elpy is not being maintained. Removed - start time < 5 seconds.
CLOSED: [2025-09-29 Mon 13:03]
** slime-auotloads had to be commented out after removing;
** re-adding quicklisp-slime-helper-master did NOT restore slimeautoloads.
so changed init.el:

(setq inferior-lisp-program "/opt/homebrew/bin/sbcl")
(add-to-list 'load-path "~/.emacs.d/elpa/slime-20250918.2258/")
(require 'slime-autoloads)
(eval-after-load "slime"  '(progn (slime-setup '(slime-fancy))))

;;     (slime-setup)

(load (expand-file-name "~/.quicklisp/slime-helper.el"))

-----------------------------------------------------------------------------------

Here's a list of packages removed:

 ace-window-20220911.358
 avy-20241101.1357
 cfrs-20250729.1422
 compat-30.1.0.1
 cond-let-20250903.1646
 dired-hacks-utils-20240629.1906
 elpy-20250404.2349
 hydra-20250316.1254
 macrostep-20250202.2205
 markdown_example.md
 pfuture-20220913.1401
 posframe-20250211.110
 trashed-20230811.157
 yasnippet-20250602.1342
* COMPLETED try UV for Python? -- installed on New. -- it works.
CLOSED: [2025-10-03 Fri 10:04]

* COMPLETED Fooled around with c programs to test clang. Everything working for compile. No linting.
CLOSED: [2025-10-03 Fri 14:05]
* COMPLETED Freeze init.el and work on other things. freezeNew06OCT.init.el is latest good b/u.
CLOSED: [2025-10-03 Fri 14:40]* WAITING Prot emacs runs as GUI on New, as terminal app on Big. Why?
** Comparison of Info.plist on New and Big showed no diff.  Both emacs in Applications are 30.2
both brew emacs are /opt/homebrew/bin/emacs BUT menu on New, after pressing f10 is different from menu on Big.
This indcates that something is different.ech
** emacsclient -c does open a new GUI frame.
*** emac in /Applications/ does open faster than starting emacs --daemon then running emacsclient -c. but emacsclient -n $1 opens a file instantly if emacs is open and server is running.
Still not sure why Big opens emacs in terminal while New opens with GUI.
** on Big /opt/homebrew/bin/emacs -q -l ~/project//Prot//init.el opens brew emacs. Not on New.
on new same command opens /Applications//emacs.app n idea why.
* lisp programming.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.
$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject:
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
<<<<<<< HEAD
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
* NEXT Look at integrating ruff with emacs. Three packages in Packages.
** ruff installed via uv/pip. config added to init.el on New.
Homgulated init.el on new and ~/project/init.el.org lines 501 to 511. Also note: lines 553 to 555 commented out on init.el new but not on
~/project/init.el.org .
** Test ruff. -- appears to format, does it lint? Need to read docs.
