* December.
* _Start times from _< 3_  on New,  and 7+ for Big,_
* Backup *init.el* then choose one language; iisp, rust, python and remove all others.

** Make sure syntax highlighting, completion and marginalia all working with the one language.
** Rinse and repeat for the other two languages.
**  lisp programming. see backup init.el below.
*** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
*** lisp is a mess. Tools are installed but need more time getting used to them.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.

$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Had to re-add quicklisp, quicklisp-slime-helper on Big.
** Rust stuff see Backup init.el below.
** Test rust to see what's actually connecting lsp-wise. Linting, formatting?
*** restarted and tried again and both .py files were linted and completed with pylsp server.
*** added spaces, not tabs and prettify, also tree-sitter integration on New's init.el:
* Misc.
** COMPLETED Project on Big not showing all files. Removed folder and cloned again.
CLOSED: [2025-11-18 Tue 11:16]
** COMPLETED removed duplicate rust dirs from ~/project/rust.
CLOSED: [2025-11-18 Tue 11:15]
** COMPLETED On New removed /Applications//Emacs.app and /opt/homebrew//bin/emacs then did: 
CLOSED: [2025-11-24 Mon 11:14]
brew install -f emacs-app )force to overlook existing man pages, etc.
** This is version 30.2 and should do native compilation <-- faster than compile.
** Commented out all compile instructions in early.init.el and init.el
Startup time < 4 seconds. Have to see if there's any downside.
** Work with this setup on New for a while and see if okay then do the same with Big.
** Added (setq package-native-compile t) to init.el
** COMPLETED Installed Treemacs. Testing.
CLOSED: [2025-11-24 Mon 11:14]
** treemacs installed ace-window, pfuture, posframe, maybe macrostep?
added:
(use-package treemacs
        :ensure t)
        
** COMPLETED ~/project/testdir/init.el and project/small.init.el are the same.
CLOSED: [2025-12-01 Mon 13:40]
** COMPLETED Homogulated init.el on Big and New and init.el.org. As freezeBoth01DEC.init.el
CLOSED: [2025-12-01 Mon 13:40]
** DONE Created new minimal init.el in ~/project/testdir/ will test at work and try on Plucky later.
CLOSED: [2025-12-03 Wed 09:20]
**  Copied that simpler init.el with additions, tested, then placed in testdir as small.init.el
copy this to Plucky and test. If has correct basic org setup
** might have to install fonts - Jetbrains and Source Code Pro  <-- changed the small init to Jetbrains for all fonts.
** note: there's small.init.el on New and in project then there's the init.el in testdir. Differences?
** COMPLETED Looking at packages that are installed but not needed. all-the-icons-dired: when I added
CLOSED: [2025-12-03 Wed 13:47]
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)  to init.el I got duplicated icons in a dired buffer. Removed this line.
Deleted some packages that appeard to be not needed. Again, this is on New only.
** Disabled paredit because it throws compile warnings and doesn't seem that useful.
Is working on Big.
** enabling slime-helper.el on line 584 causes emacs to freeze on launch.
un-re-installing slime-helper does not resolve issue no exact location when emacs --debug-init but error mentions -*-
which sounds like it's chocking on a lexical scope line.
*** Slime throws errors on native compile. - is slime-helper issue slime related.
** COMPLETED Removing tree-sitter from Elpa broke emacs w/ fatal exception. Tree-sitter ;; out in init.el
CLOSED: [2025-12-11 Thu 13:44]
Had to remove all references to tree-sitter to fix.
Will need to examine to figure out what happened.
Here's the part of init.el that broke things:
;; (use-package rust-mode   _<-- enabling these three line stops emacs loading_
;;   :init
;;   (setq rust-mode-treesitter-derive t))
;; ;; or just for rust-mode
;; ;; (add-hook 'rust-mode-hook #'tree-sitter-mode)
;; ;; Load the language definition for Rust, if it hasn't been loaded.
;; ;; Return the language object.
;; (tree-sitter-require 'rust)
;; (tree-sitter-require 'python)
;; (global-tree-sitter-mode)  _<-- this line_
;; (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode) _<-- this line_
*** Above works on Big. What's different?
*** Will consider re-enabling if I feel like I'm missing some functionality.
** problem with emacs-lisp mode - error is with rustic, which should not be involved.
Did get a lisp file for do completion and marginalia but still getting rustic errors.
** Commenting out Rustic on New temporarily to see if it fixes lisp issue.
** COMPLETED Installing rust-analyzer on new fixed server issue -  rustup component add rust-analyzer
CLOSED: [2025-12-03 Wed 09:19]
* COMPLETED Broke init.el by adding lexical binding to quicklisp files. will have to figure out how to remove.
CLOSED: [2025-12-03 Wed 13:51]
** Re-installed slime-helper.el
* COMPLETED Installed +emacs-plus 30+ w/ native compile and am using it via en alias.
CLOSED: [2025-12-05 Fri 07:28]
** Old emacs 30.2 from brew seems to still be in Applications although shortuct was sent.
** COMPLETED M-: (native-comp-available-p) <-- we don't have native compile evidently. 30.2
CLOSED: [2025-12-04 Thu 08:07]
** Tried installing emacs-plus@31 via brew. Might have to remove everything on Plucky, use this.
** COMPLETED Check paredit and smartparens<- native compile issue.
CLOSED: [2025-12-04 Thu 08:07]
** Paredit threw warnings but works fine.
** Smartparens
(setq native-comp-speed -1)  will kill native compile if put in early.init <-- didn't need.

(setq native-comp-jit-compilation-deny-list '("sentence-navigation")) <-- didn't need.

+Did this instead:+
(use-package smartparens
  :ensure smartparens  ;; install the package
  :hook (emacs-lisp-mode-hook common-lisp-mode-hook lisp-mode-hook)
  :config
  ;; load default config
  (require 'smartparens-config))
** COMPLETED Structure-template-alist commented out in init.el but not needed.
CLOSED: [2025-12-04 Thu 08:18]
#+begin_src emacs-lisp
#+end_src
still works since alist is saved (as customized item?) with the correct settings.
** COMPLETED problem is:   (load (expand-file-name "~/.quicklisp/slime-helper.el")) says -*- is issue.
CLOSED: [2025-12-03 Wed 13:51]
** on +New+: ec does now work. Emacsclient.app gives GUI ez works as intended en works.
alias ec='/opt/homebrew/bin/emacsclient -n $1'  does work, wasn't Yesterday.. Flashed when it opened then closed immediately.apl1029
* COMPLETED Changed editor = emacs in git.
CLOSED: [2025-12-09 Tue 14:51]
* COMPLETED Bookmarks, C-x r m  C-x rb C-x r l
CLOSED: [2025-12-09 Tue 14:52]
(with-eval-after-load 'desktop
  (add-to-list 'desktop-minor-mode-handlers '(eglot--managed-mode . ignore)))
  (add-to-list 'desktop-minor-mode-handlers '(eglot--managed-mode . ignore))
  (add-to-list 'desktop-minor-mode-handlers '(eglot-inlay-hints-mode . ignore)))
* COMPLETED edited ~/.cache/emacs/var/project-list.el to add correct project dirs.
CLOSED: [2025-12-10 Wed 09:27]
** Eglot cant find project on Big. error is eglot  Failed to load workspace.
* COMPLETED removed Apple, Kitty & Jamf entries from .zshrc PATH and updated all references to python.
CLOSED: [2025-12-10 Wed 11:24]
python 3.13.1 to 3.14.0
* COMPLETED Friday 12DEC.  - Enabled flycheck in New, Big and init.el.org (w/o Elpy):
CLOSED: [2025-12-12 Fri 13:49]

(use-package flycheck
  :ensure t
  :config
  (add-hook 'after-init-hook #'global-flycheck-mode))
**  NOTE: New, init.el.org, and Big have simplifed Flycheck (w/o Elpy).
* Native compile working on New. and Big. Can't compile 30.2 on Plucky.

/opt/homebrew/opt/emacs-plus@30/bin/emacs  <-- Native (is alias to below).

/opt/homebrew/Cellar/emacs-plus@31/31.0.50/Emacs.app/Contents/MacOS//Emacs   <-- alias in /Applications goes here.
(this is a script that sets the PATH variable then launches Emacs-real (the actual executable).

/opt/homebrew/bin/emacs <-- (is alias to above).
* TODO Eglot fails to discover rust or python workspaces. Python is working w/ syntax, Marginalia, etc.

* json errors. why? -- may be hint related.
(setq-local lsp-inlay-hint-enable t)

