March.
* _Start times ~ _3  on New,  and ~ 4 for Big,_
<<<<<<< HEAD
* Misc.
*** /snap/bin/emacs %F installed. Throws errors but is better than previous /usr/local/bin/emacs-30.2
Snap version is 31.0.50. not 30.2 
*** Focus follows mouse in Terminal:
defaults write com.apple.Terminal FocusFollowsMouse -string YES
** Vterm works and has correct $PATH.
** Rebuilt: Big failed after update. Reticulating Splines after restart. Could not clear it.
had to re-image the machine.
** Notes in the black book, including all software that needed install via brew.
** 560 natively compiles items in ~/.cache/emacs/eln-cache/
** Tried changing hl-line
Didn't work using: (set-face-background 'hl-line "Magenta")

Might try:

(use-package hl-line                                                                                                                                                                                                                                          :custom-face
  (hl-line ((t (:background "#FF00FF")))))

  Yeah, that didn't work either. Low priority, leave if for now.
  
** ODD thing, init.el.org had a missing '+' in one of the the #+begin_src emacs-lisp lines
this threw an error at the BOTTOM of the source block even though #+end_src was fine.
** Lisp projects go into ~/.quicklisp/local-projects/  +change that?+ _no_.
** Maze;
1. Turn right.
2. Can't turn right? Go forward.
3. Can't do 1or 2 turn left.

** "Debugging" David J. Agans
** Issue with id-locations - org roam. Fixed after org-id-update-id-locations run multiple times.
** recentf-save-list --> ~/.cache/emacs/var/recentf-save.el
** _init.el_ keeps getting corruped. Saved 12MAR_FREEZE.init.el to project dir.
** Tab function doesn't work in scratch buffer or org buffer. Also completions mess with Tab.
this is expected behavior save buffer as a program file (.lisp, .py, etc.) or enable text-mode.
** (let ((org-confirm-babel-evaluate nil)))  <-- should I toggle this customize then remove this line? NO
this is fine, just allows emacs to eval code blocks when tangling w/o user being prompted for each block.
** Completed Eglot With Rust to eliminate lsp-mode & lsp-ui ? <-- rust working well!
CLOSED: [2026-03-20 Fri 11:28]
** added defer to lsp-mode -- test this.
** Move load-path up from 589~ closer to top? Yes, done.
** Started misc-notes.org and copying everything from black notebook to org.
** Notes copied from paper to notebook.org
** COMPLETED On +Plucky+ - Make 3.14 Python the version that's used by system.
CLOSED: [2026-03-21 Sat 12:02]
* COMPLETED Cleaned up init.el on New and init.el.org - This is now the new 20MAR_FREEZE.init.el
CLOSED: [2026-03-11 Wed 09:18]
* COMPLETED LISP. Using (ql:quickload "cl-project") then
CLOSED: [2026-03-20 Fri 11:15]
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:

drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:

(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.
* COMPLETED Friday 20MAR did +pip install 'python-lsp-server[all]'+nn
CLOSED: [2026-03-20 Fri 11:17]
Python *appears* to be working properly with completions, etc.
* COMPLETED RUST syntax highlighting and completieon working. Python /seems/ to be working.
Commented out; rust mode
CLOSED: [2026-03-24 Tue 11:10]
* Look at journal or org-roam for ability to step back in time to see changes.
** Testing org roam daily.
** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
** Majpr feature of Roam is ability to x-linkg notes and a db so search is easier.
* NEXT installed emacs 30.2 via snap on +Plucky+. Works but:
** Had to remove all refs to treemacs and nerd-icons.
** other issues. Works for now w/ GUI and is in the Menu.
** Note: /usr/local/bin//emacs-30.2 throws treesit error. The snap verson /snap/bin/emacs %F doesn't.
** On +Plucky+ Native compile working on Big & New. Can't byte compile 30.2 on Plucky.
** installed 30.2 on Ducky via Homebrew. Check if native compile works.
* NEXT Ducky is on emacs 28 so many packages don't work correctly.
* WAITING Experiment more with dired.
* WAITING slime-helper still an issue. Updated slime version then uncommented slime-helper line BUT
emacs humg on load, again. Hard to comment out slime-helper line. This is *after* I re-installed slime-helper using ql in SBCL.
** Had to comment out slime-helper. Why?
* 24MAR on +New+: made changed to section after line 426 - eglot. This affected Python, maybe?
there were dulicate lines. Removed them and re-organized through  to 499.
* Commented out; paredit, global-tree-sitter-mode Paredit probably not needed.
** Is Paredit needed?
*
