* September.
* _Start times around 5 seconds, 6 for Big_, up from 3. 
* COMPLETED Removed Re-installed elpy. Uncommented elpy/flycheck code at bottom of init.el
CLOSED: [2025-08-25 Mon 12:32]
now Python code appears to be getting full language checking, linting, marginalia, etc.
* COMPLETED Had to disable zscaler to get 15.6 update to install on New.
CLOSED: [2025-08-14 Thu 14:42]
** COMPLETED After above I updated init.el.org and tangled.
CLOSED: [2025-08-19 Tue 14:35]
newtest.el showed a number of items theat need to be adressed;
auto-compile version wrong (old) some items missing that are in New's init.el etc.
** COMPLETED all ls aliases NOT for eza fail with:
** updated gems via rbenv. Set rbenv global. updated color ls. set clocale.
CLOSED: [2025-08-19 Tue 14:42]
**  opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1421:in 'block in Gem::Specification#activate_dependencies': Could not find 'clocale' (~> 0) among 95 total gem(s) (Gem::MissingSpecError)Checked in 'GEM_PATH=/Users/charles.marano/.gem/ruby/3.4.0:/opt/homebrew/lib/ruby/gems/3.4.0:/opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/gems/3.4.0' at: /opt/homebrew/lib/ruby/gems/3.4.0/specifications/colorls-1.5.0.gemspec, execute `gem env` for more information
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1407:in 'Array#each'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1407:in 'Gem::Specification#activate_dependencies'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems/specification.rb:1389:in 'Gem::Specification#activate'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:290:in 'block in Gem.activate_bin_path'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:289:in 'Thread::Mutex#synchronize'
        from /opt/homebrew/Cellar/ruby/3.4.5/lib/ruby/3.4.0/rubygems.rb:289:in 'Gem.activate_bin_path'
        from /opt/homebrew/lib/ruby/gems/3.4.0/bin//colorls:25:in '<main>'

** COMPLETED Big blew up with Vertico errors related to consult, etc.
CLOSED: [2025-08-19 Tue 14:34]
Tried a delete and re-install of GNU Emacs 30.2 for Mac. Did not fix the issue.
Tried pruning changes made this morning. Nope.
Tried copying a good init.el to Big, same vertico error:
Tried commenting out large portions of ORG section. Nope.
Tired deleting Emacs 30 .plist. Nope.
Whacked huge sections of init.el and that erased error.
----
Copied init.el from New to Big then *commented out Vertico and marginalia sections.*
Then removed -   pacakge-delete  - vertico ad marginalia.
No warnings and Org docs display correctly BUT no completion
** COMPLETED Changes to init.el on New and Big.
CLOSED: [2025-08-19 Tue 14:45]
Added below lines to init.el statup time went to 7+ seconds. 9 for Big.

** from Prot's big init?
line 319 (add-hook 'org-mode-hook 'visual-line-mode)

line 329 (setq org-hide-emphasis-markers t)

** C-x, C-f defaults to ~/
line 53 (setq file-name-shadow-properties '(invisible t))
            (file-name-shadow-mode)
*** I'd prefer a situaton where it stays in current dir until you type ~/.bashrc

***  see below. might not need this.

** typing deletes selection.
line 56 (delete-selection-mode 1)

* COMPLETED ~/org/3.org on Plucky overwrote ~/projects/org/3.org lost latest notes.
CLOSED: [2025-09-08 Mon 14:32]
restored ~/project/MyStuff/PrevOrg/2n.org to ~/project/org/3.org after renaming 3.org for Plucku as localTOPlucky.org
* COMPLETED changed GC in early-init.el and init.el :def t for all programming items.
CLOSED: [2025-09-08 Mon 14:33]
statup time rduced to ~5 secs.
* COMPLETED Reconciled init.el on New and Big. - 10SEP. 
CLOSED: [2025-09-10 Wed 12:59]
* lisp programming.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.
$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject:
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
<<<<<<< HEAD
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
* WAITING Prot emacs runs as GUI on New, as terminal app on Big. Why?
* NEXT Freeze init.el and work on other things.
