;;; +sep+
#+property: folded
* misc
** Super Special Science Daisakuso-naku Kubo Monogatari - Earth SOS

** https://en.wikipedia.org/wiki/Look-and-say_sequence
** Onani Master Kurosawa
* +latest+ 02SEP_Big.init.el, 02SEP_New.init.el & 16jul.zshrc
** COMPLETED org-structure-templates are working as they should.
CLOSED: [2026-08-20 Thu 08:12]
<KEY then <TAB> produces code block. built in L, H, A, i are disabled.

#+begin_src rust

#+end_src

#+begin_src emacs-lisp

#+end_src

#+begin_src python

#+end_src
*** ISSUE +NOTE:+ inserting code blocks: you can use <KEY then <TAB>.
CLOSED: [2026-08-03 Mon 10:02]
as in <s then l for Lisp, <s followed by L for emacs-lisp, etc.
this is instead of C-c C-,   
** COMPLETED flycheck and elisp files:
CLOSED: [2026-09-01 Tue 11:15]
*** COMPLETED Disabled flycheck for emacs lisp on new:
CLOSED: [2026-08-20 Thu 08:16]
#+begin_src emacs-lisp
(with-eval-after-load 'flycheck
  (setq-default flycheck-disabled-checkers '(emacs-lisp-checkdoc)))
#+end_src
>> this is at line 634 near the bottom of the init.el file <<
*** you can disable flycheck based on extension:
(add-hook 'flycheck-mode-hook #'my-keep-flycheck-off)

(defun my-keep-flycheck-off ()
  (when (and (eq major-mode 'sh-mode)
             (buffer-file-name)
             (string= (file-name-extension (buffer-file-name)) "cfg"))
    (flycheck-mode -1)))
***  or (setq flycheck-disabled-checkers '(sh-shellscript sh-bash sh-zsh))
*** or, again:
(add-to-list 'auto-mode-alist
             '("\\.cfg\\'" . (lambda ()
                               (setq flycheck-disabled-checkers  (append '(sh-shellscript sh-bash sh-zsh)
                               flycheck-disabled-checkers))
                               (shell-script-mode))))

*** NOTE: For instance, the first syntax checker for Emacs Lisp is emacs-lisp which checks Emacs Lisp with Emacs’ own byte compiler. This syntax checker asks for emacs-lisp-checkdoc to run next, which checks for stylistic issues in Emacs Lisp docstrings. Thus Flycheck will first run the byte compiler and then checkdoc in an Emacs Lisp buffer.

*** https://danliden.com/posts/20250330-emacs-debugging.html
disabled #(add-hook 'after-save-hook 'eglot-format))#
** COMPLETED Copied rainbow-delimiters from ~/.emacs.d/straight/repos/
CLOSED: [2026-08-20 Thu 08:16]
** COMPLETED Added my-split-window-func to New (was on Big)
CLOSED: [2026-08-20 Thu 08:16]
#+begin_src emacs-lisp
(defun my-split-window-func ()
  (interactive)
  (split-window-below)
  (set-window-buffer (next-window) (other-buffer)))

(global-set-key (kbd "C-x 4") #'my-split-window-func)
#+end_src

*** This did NOT increase load time for init.el on New so...
Longer load time for init.el on Big still needs investigating.

* DONE rpc error fix?
CLOSED: [2026-09-02 Wed 09:36]
(remove-hook 'after-save-hook #'eglot-format nil)
** problem seems to be with eglot and is triggered by a save.
* ISSUE init.el on Plucky is a mess.
* ISSUE emacs versions @ /usr/bin/emacs -nw %F & home/linuxbrew/.linuxbrew/bin//emacs
* ISSUE Build emacs:
CLOSED: [2026-08-19 Wed 13:24]
https://deepwiki.com/emacsmirror/emacs/6-building-and-extending-emacs
* WAITING +emacs 31+... speedbar. Bind it to a function key maybe?
* NEXT Try Macro recording at some point.
C-x ( starts recording a macro
C-x ) stops recording a macro
C-x e executes the macro
C-u 37 C-x e executes the macro 37 times
C-u 0 C-x e executes the macro an infinite number of times until EOF.
* NOTE: Lisp scripts:
#!/opt/homebrew/bin/sbcl _<-- needs to run with sbcl --script <filename>_

#!/opt/homebrew/bin/sbcl --script +<-- can just do ./<filename>+

** Lisp
** cl-project throws errors. Use quickproject for now?
*** throws an HTTPS statuse error 
*** (cl-project:make-project #p"lib/cl-sample/")

(ql:quickload :quickproject)

(quickproject:make-project #p"~/project/lisp/my-quickproject-test/")
** lisp scripts
Create a file named hello (you can drop the .lisp extension) and add this:

#+begin_src lisp
#!/opt/homebrew/bin/sbcl --script
(require :uiop)
(format t "hello ~a!~&" (uiop:getenv "USER"))
#+end_src
Make the script executable (chmod +x hello) and run it:

$ ./hello
hello me!

+above method works+
-------
;; filename.lisp
;; note the --script switch, not needed for raw code? NOPE, _doesn't display either way._
~(print "hello world")~
And then we run this in the terminal:

#+begin_src lisp
sbcl --script filename.lisp
"hello world"
#+end_src

+this also works+
===========
--load
If you use --load, then it will evaluate everything in your file, and then drop you into
an interactive prompt so that you can interact with your program:

So let’s say we have the following file:

#+begin_src lisp
;; filename.lisp
(defun sum (list)
  (if list (+ (car list) (sum (cdr list))) 0))
#+end_src

And we call --load in the terminal:

$ sbcl --load filename.lisp
#<some preamble about sbcl you can ignore>
then you enter the following:

*** (sum '(1 2 3 4 5))
15

+Above works+
---------
clisp <filename> runs a lisp script.
clisp -repl <filename> runs a script then drops to the repl.
_^That's like sbcl --load^_


(above examples are from: https://comp-348.github.io/lisp-running-from-terminal.html)
----------
#+begin_src lisp
(defconstant +year-size+ 365)

(defun birthday-paradox (probability number-of-people)
  (let ((new-probability (* (/ (- +year-size+ number-of-people)
                               +year-size+)
                            probability)))
    (if (< new-probability 0.5)
        (1+ number-of-people)
        (birthday-paradox new-probability (1+ number-of-people)))))
#+end_src

Calling the example function using the REPL (Read Eval Print Loop):

CL-USER > (birthday-paradox 1.0 1)
23
-----------
#+begin_src lisp
(defclass person ()
  ((name :initarg :name :accessor person-name)
   (age  :initarg :age  :accessor person-age))
  (:documentation "The class PERSON with slots NAME and AGE."))

(defmethod display ((object person) stream)
  "Displaying a PERSON object to an output stream."
  (with-slots (name age) object
    (format stream "~a (~a)" name age)))

(defparameter *group*
  (list (make-instance 'person :name "Bob"   :age 33)
        (make-instance 'person :name "Chris" :age 16)
        (make-instance 'person :name "Ash"   :age 23))
  "A list of PERSON objects.")

(dolist (person (sort (copy-list *group*)
                      #'>
                      :key #'person-age))
  (display person *standard-output*)
  (terpri))
#+end_src

It prints the three names with descending age.

Bob (33)
Ash (23)
Chris (16)

#+begin_src lisp
(defun list-matching-lines (file predicate)
  "Returns a list of lines in file, for which the predicate applied to
 the line returns T."
  (with-open-file (stream file)
    (loop for line = (read-line stream nil nil)
          while line
          when (funcall predicate line)
          collect it)))
#+end_src

#+begin_src lisp
(defun available-shells (&optional (file #p"/etc/shells"))
  (list-matching-lines
   file
   (lambda (line)
     (and (plusp (length line))
          (char= (char line 0) #\/)
          (pathname
           (string-right-trim '(#\space #\tab) line))))))
#+end_src
* Org speed keys.
Speed Keys
Single keystrokes can execute custom commands in an Org file when point is on a headline. Without the extra burden of a meta or modifier key, Speed Keys can speed navigation or execute custom commands. Besides faster navigation, Speed Keys may come in handy on small mobile devices that do not have full keyboards. Speed Keys may also work on TTY devices known for their problems when entering Emacs key chords.

By default, Org has Speed Keys disabled. To activate Speed Keys, set the variable org-use-speed-commands to a non-nil value. To trigger a Speed Key, point must be at the beginning of an Org headline, before any of the stars.

Org comes with a pre-defined list of Speed Keys. To add or modify Speed Keys, customize the option org-speed-commands. For more details, see the variable’s docstring. With Speed Keys activated, M-x org-speed-command-help, or ? when point is at the beginning of an Org headline, shows currently active Speed Keys, including the user-defined ones.
* Org structure templates
Structure Templates ¶
With just a few keystrokes, it is possible to insert empty structural blocks, such as ‘#+BEGIN_SRC’ … ‘#+END_SRC’, or to wrap existing text in such a block.

C-c C-, (org-insert-structure-template)
Prompt for a type of block structure, and insert the block at point. If the region is active, it is wrapped in the block. First prompts the user for keys, which are used to look up a structure type from the variable below. If the key is TAB, RET, or SPC, the user is prompted to enter a block type.

Available structure types are defined in org-structure-template-alist, see the docstring for adding or changing values.

Org Tempo expands snippets to structures defined in org-structure-template-alist and org-tempo-keywords-alist. For example, < s TAB creates a code block. Enable it by customizing org-modules or add ‘(require 'org-tempo)’ to your Emacs init file162.

a	‘#+BEGIN_EXPORT ascii’ … ‘#+END_EXPORT’
c	‘#+BEGIN_CENTER’ … ‘#+END_CENTER’
C	‘#+BEGIN_COMMENT’ … ‘#+END_COMMENT’
e	‘#+BEGIN_EXAMPLE’ … ‘#+END_EXAMPLE’
E	‘#+BEGIN_EXPORT’ … ‘#+END_EXPORT’
h	‘#+BEGIN_EXPORT html’ … ‘#+END_EXPORT’
l	‘#+BEGIN_EXPORT latex’ … ‘#+END_EXPORT’
q	‘#+BEGIN_QUOTE’ … ‘#+END_QUOTE’
s	‘#+BEGIN_SRC’ … ‘#+END_SRC’
v	‘#+BEGIN_VERSE’ … ‘#+END_VERSE’
