
* July
* Start times around 3 seconds.
** New taking 3+ seconds. Big now taking 9+ seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
* COMPLETED Tried Aerospace tiling WM. It immediately bugged out so leave for later.
CLOSED: [2025-06-09 Mon 10:27]
* COMPLETED installed fd very nice find replacement.
CLOSED: [2025-06-19 Thu 08:22]
* COMPLETED Installed eza - seems faster than ls.
CLOSED: [2025-06-19 Thu 08:22]
** created aliases:
alias lz='eza -lh --color=always --icons=always'
alias ly='eza -lha --color=always --icons=always --group-directories-first'
*** WAITING Love eza. Did alias it as lz.
Tmux or Kitty, etc. w/ split windows, tabs?
* COMPLETED Still fighting w/ themes on Tmux. got Nord to load, see which .tmux.conf worked.
CLOSED: [2025-06-26 Thu 09:46]
** Can't get any theme to load for Tmux on Big. Strangely, it does accept C-a
so it is reading a changed conf from somewhere. I've tried cp the .tmux.conf file to /opt/homebrew//etc and to
~/.tmux/ with no change. Removed all except ~/.tmux.conf
** theme was working on New but changing it and doing comand : source ~/.tmux.conf broke it.
** Okay, weird. Changing back to Nord Them worked on New.
** Running the command : source-file ~/.tmux.conf on Big put catppuccin theme in.
run '~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux'     <-- added to ~/.tmux.conf
** Okay, so putting set -g @plugin "nordtheme/tmux'
then run ~/.tmux/plugins/tpm/tpm did the trick. Now have Nord theme on both Big and new.
** Next step: try powerline
** Nord theme was okay w/ Tmux. Haven't seen anything superior yet.
** Tried Catppuccin theme - won't load, stuck on Nord.
* COMPLETED Installed kkp package for kitty-protocol in emacs.
CLOSED: [2025-06-30 Mon 13:53]
* COMPLETED Installed Yazi on New. Looks interesting. 
CLOSED: [2025-06-30 Mon 14:00]
** looks like a pain to customize. Will try it and see.
** changed yazi proportions to 1, 3, 4.
** +was able to change yazi theme on big and new to dracula, then mocha.+
ya pack -a yazi-rs/flavors:dracula
*** was able to change flavor to dracula.
*** yazi themes not working correctly on New. Can't set theme w/ any flavor.
*** downloaded cattpuccin and dracula themes and got dracula set (Cattpuccin too dull.
*** other flavors don't seem to work.
tried copying and renaming vscode-dark-plus to foo and setting that in theme.toml ... no good.
+so,,,+
*** Okay, so +took catppuccin-mocha-green.toml, copied it into ~/.config/yazi and changed its name to theme.toml+
that worked. Now have this theme (not flavor) on Big and New.
* COMPLETED  Run this on Big git config --global credential.helper store - didn't work.
CLOSED: [2025-07-02 Wed 08:22]
=======
* COMPLETED Added to tmux.conf:
CLOSED: [2025-07-02 Wed 13:09]
set -g allow-passthrough on
set -g update-environment TERM
set -g update-environment TERM_PROGRAM
>>>>>>> 5a7e4ca (Cycling through 3.org for July)
* COMPLETED +was able to change yazi theme on big and new to dracula, then mocha-green
CLOSED: [2025-07-02 Wed 08:23]
** ya pack -a yazi-rs/flavors:dracula
*** was able to change flavor to dracula.
*** yazi themes not working correctly on New. Can't set theme w/ any flavor.
*** downloaded cattpuccin and dracula themes and got dracula set (Cattpuccin too dull.
*** other flavors don't seem to work.
tried copying and renaming vscode-dark-plus to foo and setting that in theme.toml ... no good.
+so,,,+
*** Okay, so +took catppuccin-mocha-green.toml, copied it into ~/.config/yazi and changed its name to theme.toml+
that worked. Now have this theme (not flavor) on Big and New.
** Still a little confused. catppuccin-mocha-green is on Big and New but other remnants of themes remain.
investigate and clean up at some point.
* COMPLETED Emacs on Big takes 7 secs. to open vs. 3 for New.
CLOSED: [2025-07-03 Thu 08:30]
** Do a diff on their init.el files. - New and Big homogulated July 2nd.
** Check number of packages loaded. -- 61 pacakges Big and New.
* COMPLETED Ghostty on New won't show working directory.  Okay, now it does on New and Big.
CLOSED: [2025-07-07 Mon 09:23]
** Kitty will scroll with C-<shift> and page up, page down, home and end. 
 in Tmux, have to go to copy mode C-a [ then q when ready to quit.
** Ghostty doing two line prompt but is throwing error in shell integration file. - fixed?
error in /Applications//Ghostty.app//Contents/Resources/ghostty/shell-intergration/zsh//ghostty-integration line 317.
was able to remove zsh integration. Removing zsh integration was annoying.
Modified kitty.conf to remove 'are you sure' dialog when closing. 

**  Had to re-install Ghostty then added to .zshrc:
*** added on both New and Big.

 if [[ -n $GHOSTTY_RESOURCES_DIR ]]; then
 source "$GHOSTTY_RESOURCES_DIR"/shell-integration/zsh/ghostty-integration
fi

* COMPLETED What's my github password?
CLOSED: [2025-07-07 Mon 09:24]
it's in gitpas.txt on the Desktop.
* COMPLETED Github Python branch not set up for https, couldn't update
CLOSED: [2025-07-07 Mon 09:24]
* COMPLETED Yazi very simple to use. Commands make sense.
CLOSED: [2025-07-07 Mon 12:37]
* COMPLETED Use bat, not cat, when syntax highlighting is important.
CLOSED: [2025-07-08 Tue 13:51]
** alias cat to bat in .zshrc or make other aliases?
* COMPLETED Note: flatpak not used on Big and New.
CLOSED: [2025-07-09 Wed 14:56]
* COMPLETED On Big: couldn't delete yasnippet dir that was throwing errors. Dir had no snippets.
CLOSED: [2025-07-14 Mon 14:46]
I created an empty snippets dir inside the Yasnippet Dir and that stopped the error messages. Still why couldn't I just
delte the dir out of yas-snippet-dirs?
* COMPLETED Installed lazygit. Have to try it out. Not needed right now.
CLOSED: [2025-07-17 Thu 13:05]
* COMPLETED Messed around with Markdown. Can read it in emacs but not important right now.
CLOSED: [2025-07-17 Thu 13:04]
* COMPLETED Tmux not needed right now. Don't need multiple terminal sessions at this time.
CLOSED: [2025-07-17 Thu 13:06]
* COMPLETED Generated pgp key pair.
CLOSED: [2025-07-17 Thu 13:50]
* COMPLETED added Helpful package.
CLOSED: [2025-07-21 Mon 13:54]
* TODO Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* TODO Trying to figure out project root.
* TODO Test gh on Big to see if ssh key works there.
* WAITING Terminal testing. Wezterm is sharpest. On Big and Plucky
** Wezterm seesm Windows friendly. Ghostty is Mac Friendly.
** Kitty and wezterm are the sharpest, clearest. Iterm is fuzzy,  ghostty is so-so.
westerm uses Lua, not a fan. Ghostty uses Zig. Kitty is combo of C and Python.
*** Changed Wezterm theme to MaterialDesignColors, trouble changing bg.
** Actually side by side Ghostty looks sharpest, followed by wezterm. Kitty is 3rd, iTerm2 last.
to 344449 <-- which is the color that the Material Design theme I d.l.'s for iTerm2 uses.
I did change Ghostty and Kitty themes on New to use that color for background. I term already uses it.
Speed?. <-- variable all show lag at some point.icon size - Jetbrainsmono has larger icons. 
*** Changed all terms to 263238
this is from Martin Seeler's Material Design iTerm2 theme Material Design.
or 344449 depends on monitor.
*** Changed font on all from Hack Nerd Font to JetBrainsMono Nerd Font.
Gave larger padding (space between lines) and larger icons, which is nice. This is default on wezterm.
*** wezterm: config.window_close_confirmation = 'NeverPrompt'
now wezterm does not prompt 'Are you sure?' when quitting.
*** wezterm can't get rid of tab bar.
*** All terms on New seem to have trouble picking up changes at some point.
*** Ghostty on Big is not picking up changes to  config. <-- wait, now it is. 
changed permissions to 666 sizing worked. Color seems fine on Big, not on new (moritor or app?)
*** bg colors really inconsistent between monitors.
*** wezterm seems to have best graphics - wyland? Probably not on Macs. Maybe it's the MaterialDesignColors theme?
** changed theme for Ghostty to MaterialDesignColors on Big and New.
fg* Added an alias to .zshrc:
alias lx='eza -lat created --color=always --icons=always --group-directories-first
** Kitty theme is Tomorrow night eighties.
** Tried kitty terminal.  It may be faster, not sure.
** Forn default, too small, editor vi, etc. Edited ~/.config/kitty/kitty.conf
** added kitty-themes to .config/kitty. Chose MaterialDark.
** set up kitty on Big. Different themes on each. New = Materialdark. Big is Tomorrow_Night_Eighties.
** kitten choose-fonts doesn't apper to work, doesn't modify kitty.conf3
** It writes a separate Kitty fonts section at THE END of kitty.conf
*** worked AFTER I gave kitty full disk access in Privacy & Security.
*** Which is better? Materialdark or Tomorrow_Night_Eighties?
*** currently using Tomorrow. May change back to Material.
** Trying WezTerm and Ghostty.
** WezTerm uses Lua to config and isn't hard. Colors look okay. Muted vs. ITerm2.
** COMPLETED Kitty disappeared on Big.
*** Had trouble re-installing. Couldn't install via homebrew. Installing via curl put kitty in /Applications/ but kitten not found.
Had to add /Applications/kitty.app/Contents/macOS to paht in .zshrc
* lisp programming.
** COMPLETED ielm did not work correctly on New or Big w/ normal emacs but DID work correctly using Prot's emacs.
CLOSED: [2025-07-16 Wed 08:47]
so something in ~/.emacs.d/init.el is wrong. Removed ALL lisp-related items and ielm started functioning normally.
** COMPLETED Installed quicklisp on Big and New:
CLOSED: [2025-07-16 Wed 08:47]
readded paredit info to init.el slime working. added rainbow delimeters and eldoc mode. All work correctly.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.
$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject:
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
** Did re-install of Quicklisp on New and Big via: https://www.quicklisp.org/beta/#basic-commands
   
* NEXT Updated and tangled ~/project/init.el.org but it threw lots of errors.
** Had to clean up the resulting newtest.el by hand. Took a while.
*** Looks like tangle just failed to accurately process the org file.
** Tried tangling again after checking init.el.org against working init.el - still got errors.
*** Need to look at init.el.org and see what may have happened.
* NEXT emacs startup almost 2 secs. slower after above.
** removed yasnippet section gained 1 sec on startup time.
** What is:
_disabled_ (file-name-shadow-mode 1)
_disabled_ (add-hook 'rfn-eshadow-update-overlay-hook #'vertico-directory-tidy)
(setq delete-by-moving-to-trash t)
(setq dired-dwim-target t)

_disabled_ (setq ls-lisp-use-insert-directory-program nil)
     (require 'ls-lisp)
** disabling above did not improve startup time. Now 1 sec.
* Check to make sure smartparens is installed on Big and New.
