March.
* _Start times ~ _3  on New,  and ~ 4 for Big,_
<<<<<<< HEAD
* Misc.
*** /snap/bin/emacs %F installed. Throws errors but is better than previous /usr/local/bin/emacs-30.2
Snap version is 31.0.50. not 30.2 
*** Focus follows mouse in Terminal:
defaults write com.apple.Terminal FocusFollowsMouse -string YES
** COMPLETED Vterm works and has correct $PATH.
CLOSED: [2026-02-18 Wed 10:52]
** DONE Rebuilt: Big failed after update. Reticulating Splines after restart. Could not clear it.
CLOSED: [2026-03-09 Mon 08:41]
had to re-image the machine.
** Notes in the black book, including all software that needed install via brew.
* Installed emacs 30.2 via homebrew on Ducky.
** NEXT Ducky is on emacs 28 so many packages don't work correctly.
* DONE 560 natively compiles items in ~/.cache/emacs/eln-cache/
CLOSED: [2026-03-10 Tue 13:12]
* WAITING Lisp projects go into ~/.quicklisp/local-projects/  +change that?+
* WAITING On +Plucky+ Native compile working on Big & New. Can't byte compile 30.2 on Plucky.
** installed 30.2 on Ducky via Homebrew. Check if native compile works.
** On +Plucky+ Native compile working on Big & New. Can't byte compile 30.2 on Plucky.
* WAITING On +Plucky+ - Make 3.14 Python the version that's used by system.
* WAITING Experiment more with dired.
* Look at journal or org-roam for ability to step back in time to see changes.
** Testing org roam daily.
** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
** Majpr feature of Roam is ability to x-linkg notes and a db so search is easier.
* LISP. Using (ql:quickload "cl-project") then
(cl-project:make-project #P"./quicklisp/local-projects/my-projects/")
got a skeleton for the project and a main.lisp in the scr subdir.
looks like this:

drwxr-xr-x@    - charles.marano 25 Feb 12:55   src
drwxr-xr-x@    - charles.marano 25 Feb 12:55   tests
.rw-r--r--@   68 charles.marano 25 Feb 12:55   .gitignore
.rw-r--r--@  559 charles.marano 25 Feb 12:55   my-project.asd
.rw-r--r--@   40 charles.marano 25 Feb 12:55   README.markdown
.rw-r--r--@   41 charles.marano 25 Feb 12:55   README.org

main.lisp looks like this:

(uiop:define-package my-project
   2 │   (:use #:cl))
   3 │ (in-package #:my-project)
   4 │
   5 │ ;; blah blah blah.
* Cleaned up init.el on New and init.el.org - This is now the new 10 MAR_FREEZE.init.el
