* June
* Start times around 3 seconds.
** New taking 3+ seconds. Big now taking 9+ seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
* COMPLETED zoxide does work.
Did cd ~/.emacs.d then cd ~/project after could do cd .emacs.d
CLOSED: [2025-06-09 Mon 10:27]
and cd project.* COMPLETED emacs server / client.
CLOSED: [2025-05-22 Thu 07:42]
** put plist into launch agents folder to start emacs --daemon automatically on restart.
*** failed. using N-X server-start from emacs for now.
*** advantage is should be able to force files to open quickly in emacsclient.
*** emacs start ~3 secs. emacsclient starts in 2.37 secs. ec opens files instantly.
*** emacsclient -n <filename>  <-- reuse frame, seems to work.
*** emacsclient -a '' -c <--satarts daemon and client
*** emacs --daemon   emacs --fg-daemon emacsclient -cache
*** emacsclient --no-wait -r <filename>   <-- should reuse existing frame, doesn't.
*** emacsclient -cn <filename> &  <-- seems to work. For intial frame after emacs --daemon. _<--_
*** emacsclient --no-wait -c <filename> <-- new GUI frame. _<--works_
** Use C-x 5 0 to kill instance. _<-- works_
**  added alias to .zshrc -->   alias ec='emacsclient -n $1' +<-- use this.+
* COMPLETED Tried Aerospace tiling WM. It immediately bugged out so leave for later.
CLOSED: [2025-06-09 Mon 10:27]
* COMPLETED Note: yazi is in brew if I want to try it uses vi keybinds so no.
CLOSED: [2025-06-19 Thu 09:13]
* COMPLETED Put Emacs Elements Tangle notes in Project.
CLOSED: [2025-06-09 Mon 10:27]
** Tangled init.el.org and had lots of duplicate sections. Did tangle aadd to existing newest.el?
instead of replacing it? Will try tangling again later.
* COMPLETED Trying Yasnippet again. Added code to init.el if successful add to
CLOSED: [2025-06-09 Mon 10:27]
init.el.org and tangle so resulting file can be put in projects dir for Big and Plucky (and Ducky?).
additions to init.el are from ln 191 to ln 196.
installed yas-snippets, which show up as elpy-20250404.2349 and have python snippets only.
this and .emacs.d/snippets are only yas-snippet-dirs
** got +some+ snippets in yasnippet-snippets-20250507.2002/snippets working.
had to change < to +  since auto parens screw them up. This is a problem as any changes
I make will be lost when the yasnippet-snippets packae is updated.
** Other snippets not working. 
+remove again?+
* DONE installed fd very nice find replacement.
CLOSED: [2025-06-19 Thu 08:22]
* COMPLETED Compiled a little C program just to see if gcc was working.
CLOSED: [2025-06-19 Thu 14:38]
* COMPLETED Couldn't install uutils (written in Rust) compile failure.
CLOSED: [2025-06-20 Fri 07:56]
error: environment variable `PROJECT_NAME_FOR_VERSION_STRING` not defined at compile time
   --> /Users/charles.marano/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/uu_uniq-0.1.0/src/uniq.rs:595:18
    |
595 |         .version(uucore::crate_version!())
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: use `std::env::var("PROJECT_NAME_FOR_VERSION_STRING")` to read the variable at run time
    = note: this error originates in the macro `env` which comes from the expansion of the macro `uucore::crate_version` (in Nightly builds, run with -Z macro-backtrace for more info)

* DONE Installed eza - seems faster than ls.
CLOSED: [2025-06-19 Thu 08:22]
** created aliases:
alias lz='eza -lh --color=always --icons=always'
alias ly='eza -lha --color=always --icons=always --group-directories-first'
*** WAITING Love eza. Did alias it as lz.
Tmux or Kitty, etc. w/ split windows, tabs?
* WAITING Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* WAITING Lisp programming.
** Tried kitty terminal.  It may be faster, not sure.
** Forn default, too small, editor vi, etc. Edited ~/.config/kitty/kitty.conf
** added kitty-themes to .config/kitty. Chose MaterialDark.
** set up kitty on Big. Different themes on each. New = Materialdark. Big is Tomorrow_Night_Eighties.
** kitten choose-fonts doesn't apper to work, doesn't modify kitty.conf3
** It writes a separate Kitty fonts section at THE END of kitty.conf
*** worked AFTER I gave kitty full disk access in Privacy & Security.
*** Which is better? Materialdark or Tomorrow_Night_Eighties?
*** currently using Tomorrow. May change back to Material.
** Trying WezTerm and Ghostty.
** WezTerm uses Lua to config and isn't hard. Colors look okay. Muted vs. ITerm2.
** Ghostty is supposed to be zero config but rquired some tweaks to config.
 is doing two line prompt but is throwing error in shell integration file.
error in /Applications//Ghostty.app//Contents/Resources/ghostty/shell-intergration/zsh//ghostty-integration line 317.
was able to remove zsh integration.
modified kitty.conf to remove 'are you sure' dialog when closing. Removing zsh integration was annoying.
* NEXT Terminal testing.
*** Changed Wezterm theme to MaterialDesignColors, trouble changing bg.
to 344449 <-- which is the color that the Material Design theme I d.l.'s for iTerm2 uses.
I did change Ghostty and Kitty themes on New to use that color for background. I term already uses it.
Speed?. <-- variable all show lag at some point.
icon size - Jetbrainsmono has larger icons. 
*** Changed all terms to 263238
this is from Martin Seeler's Material Design iTerm2 theme Material Design.
or 344449 depends on monitor.
*** Changed font on all from Hack Nerd Font to JetBrainsMono Nerd Font.
Gave larger padding (space between lines) and larger icons, which is nice. This is default on wezterm.
*** wezterm: config.window_close_confirmation = 'NeverPrompt'
now wezterm does not prompt 'Are you sure?' when quitting.
*** wezterm can't get rid of tab bar.
*** All terms on New seem to have trouble picking up changes at some point.
*** Ghostty on Big is not picking up changes to config. <-- wait, now it is. 
changed permissions to 666 sizing worked. Color seems fine on Big, not on new (moritor or app?)
** Ghostty on new not doing title, seems to not pick up config changes.
*** won't do path as title, even using same config as Big.
*** Kitty seems reliable. tweaked config.
Playing around with terminals, KItty, Ghost, Weterm. Don't like weterm's Lua for config.
Kitty seems useable. Ghosty may be nice but title issue on New, Big shows directory as title.
** bg colors really inconsistent between monitors.
* tmux.conf from YouTube unbound some key combos and rebound them. Fixed!
** Now I want to decide if Tmux is worth learning or if split panes, tabs, mutiple windows that
terminal apps offer are enough.

unbind % # Split vertically
unbind '"' # Split horizontally

unbind v
unbind h

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

unbind n  #DEFAULT KEY: Move to next window
unbind w  #DEFAULT KEY: change current window interactively

bind n command-prompt "rename-window '%%'"
bind w new-window -c "#{pane_current_path}"
$
bind -n M-p previous-window
bind -n M-n next-window

** tmux read ~/.tmux.conf - confirmed.
** the only way I could change themes is to remove old theme folders from ~/tmux-plugins/ 
* Still fighting w/ themes on Tmux. got Nord to load, see which .tmux.conf worked.
