February.
* _Start times from _~ 3.5, up from 3  on New,  and ~4 for Big,_
* On +Plucky+ Native compile working on Big & New. Can't byte compile 30.2 on Plucky.
* Misc.
** On +Plucky+, terminal mode emacs doesn't give treesit error but GUI does. _investigate_
Intstalled Snap emacs (v. 28.0.2) works in graphic mode.
** On +Plucky+ init.el issue - not showing icons for org files. _org-bullets?_
Might be same issue as on New. Emacs from Snap fixed the issue.
** COMPLETED Lexical scoping on New, Big and init.el.org.
CLOSED: [2026-01-05 Mon 13:39]
** COMPLETED Tree-sitter was running globally - so modified it on New, Big, init.el.org.
CLOSED: [2026-01-05 Mon 13:35]

(require 'tree-sitter)
(require 'tree-sitter-langs)
(add-hook 'rust-mode-hook #'tree-sitter-mode)     _<-- added_
(add-hook 'python-mode-hook #'tree-sitter-mode) _<-- added_

;; (global-tree-sitter-mode)  _<-- commented out_

;; (use-package rust-mode
;;   :init
;;   (setq rust-mode-treesitter-derive t))
;; ;; or just for rust-mode
;; ;; (add-hook 'rust-mode-hook #'tree-sitter-mode) +was same on 18AUG+
;; ;; Load the language definition for Rust, if it hasn't been loaded.
;; ;; Return the language object.
;; (tree-sitter-require 'rust)
;; (tree-sitter-require 'python)
;; (global-tree-sitter-mode)  _<-- not this_
(add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode) _<-- same before (18AUG) and now (05Jan)_
** COMPLETED Removed lsp-treemacs from init.el on New and Big and init.el.org
CLOSED: [2026-01-22 Thu 10:44]
** COMPLETED on Big and New, changed .zshrc autoload -Uz compinit && compinit -i
CLOSED: [2026-01-27 Tue 13:25]
This is to stop complaint about insecure directory -  ~/.rbenv/  which looks exaclty like .pyenv
Tried chmoding and 755ing the entire .rbenv directory but did not fix issue.
Next step would be to add a line to .zshrc to ignore insecure directories.
** This is probably because root is not charles.marano so compaudit sees owner as wrong.
** COMPLETED At this point I'm considering putting Rust aside and focusing on Python.
CLOSED: [2026-01-22 Thu 10:52]

** WAITING Eglot fails to discover rust workspaces.
** Python is working w/ syntax, Marginalia, etc.
** Rust - load cargo file 1st then src file and lsp will connect without complaining. _<-- not any longer!_
** COMPLETED Something broke org-bullets during init.el cleanup on New.
fixed with command at lines 357, 348
CLOSED: [2026-02-02 Mon 12:31]
Also had duplicat exec-path-from-shell intries.
** With Lisp files - company back end not connected.
** COMPLETED command to eval init.el
CLOSED: [2026-01-29 Thu 11:02]
emacs -batch -l  ~~/.emacs.d/init.el --eval '(message "init.el loaded successfully~")'
** COMPLETED 28JAN - init.el same on New, Big and init.el.org _freeze_
CLOSED: [2026-01-14 Wed 13:13]
* COMPLETED json errors. why? -- was eglot related (after-save-hook.)
CLOSED: [2026-01-07 Wed 11:13]
** note: the below line is a dupe of <-- 519.
(setq-local lsp-inlay-hint-enable t)   <-- 533
** ruby-lsp not installed. used brew install ruby-lsp on new and big also ruff install on big.
**  On New: commenting out lines 449-450 resolved the json-rpc error.
(with-eval-after-load 'eglot
(add-hook 'after-save-hook 'eglot-format))
* COMPLETED Flycheck now working with elisp files on New & Big.
CLOSED: [2026-01-07 Wed 14:56]
** Flycheck; C-c ! v to verify setup, C-c ! n (next), C-c ! p (prev), C-c ! | (all), C-c ! e (explain).
*** No idea why it started working. Could diff older init.el files to see what changed.
*** Had to mess around with init.el after flycheck flagged lots of errors.
** COMPLETED Friday 12DEC.  - Enabled flycheck in New, Big and init.el.org (w/o Elpy):
CLOSED: [2025-12-12 Fri 13:49]

(use-package flycheck
  :ensure t
  :config
  (add-hook 'after-init-hook #'global-flycheck-mode))
**  NOTE: New, init.el.org, and Big have simplifed Flycheck (w/o Elpy).
* Eglot couldn't determine lsp-server on Big even though it says emacs-lisp.
** lisp on New is odd. Slime is enabled, but Compay wants a language server (for eglot?).
*** Flycheck does appear to be working in lisp buffers on New and Big.
isp should NOT require a language server but eglot should work with lsp-mode.
*** copied init.el from New to Big, still not checking. Does Flycheck on Big need to know what the checker is?
No, seems to know it's emacs-lisp.  C-c ! v shows everything looks o.k. on both machines.
** in Terminal: cargo locate-project --workspace --message-format plain to find Cargo.toml
* Look at journal or org-roam for ability to step back in time to see changes.
** Testing org roam daily.
** dailies go in ~/project/org/roam/daily
C-c n d n to capture a new note.
C-c n i to insert link to another note.
C-c n d d to see Today's notes.
C-c n f to see list of all notes.
** C-c c then j for  journal (and not C-c j) C-c a does open agenda.
** Org journal entries all go into the same file --> journal.org
while org roam dailies go into sepearte files (even if created on same day) with leading date.
*** how are org roam dailies and denote notes different?
* NEXT On 02FEB major changes to init.el on New, not reflected on Big on init.el.org yet.
* Lots of issues w/ init.el changes on New. It loads now. Did I fix anything?
