* December.
* _Start times from ~ 4  on New,  and 7+ for Big,_
* COMPLETED Project on Big not showing all files. Removed folder and cloned again.
CLOSED: [2025-11-18 Tue 11:16]
** COMPLETED removed duplicate rust dirs from ~/project/rust.
CLOSED: [2025-11-18 Tue 11:15]
* COMPLETED On New removed /Applications//Emacs.app and /opt/homebrew//bin/emacs then did: 
CLOSED: [2025-11-24 Mon 11:14]
brew install -f emacs-app )force to overlook existing man pages, etc.
** This is version 30.2 and should do native compilation <-- faster than compile.
** Commented out all compile instructions in early.init.el and init.el
Startup time < 4 seconds. Have to see if there's any downside.
** Work with this setup on New for a while and see if okay then do the same with Big.
** Added (setq package-native-compile t) to init.el
* COMPLETED Installed Treemacs. Testing.
CLOSED: [2025-11-24 Mon 11:14]
** treemacs installed ace-window, pfuture, posframe, maybe macrostep?
added:
(use-package treemacs
        :ensure t)
        
* COMPLETED Homogulated init.el on Big and New and init.el.org. As freezeBoth01DEC.init.el
CLOSED: [2025-12-01 Mon 13:40]
* COMPLETED ~/project/testdir/init.el and project/small.init.el are the same.
CLOSED: [2025-12-01 Mon 13:40]
* Backup *init.el* then choose one language; iisp, rust, python and remove all others.

** Make sure syntax highlighting, completion and marginalia all working with the one language.
** Rinse and repeat for the other two languages.
**  lisp programming. see backup init.el below.
*** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
*** lisp is a mess. Tools are installed but need more time getting used to them.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.

$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Had to re-add quicklisp, quicklisp-slime-helper on Big.
** Rust stuff see Backup init.el below.
** Test rust to see what's actually connecting lsp-wise. Linting, formatting?
*** restarted and tried again and both .py files were linted and completed with pylsp server.
*** added spaces, not tabs and prettify, also tree-sitter integration on New's init.el:

* NEXT Created new minimal init.el in ~/project/testdir/ will test at work and try on Plucky later.
**  Copied that simpler init.el with additions, tested, then placed in testdir as small.init.el
copy this to Plucky and test. If has correct basic org setup
** might have to install fonts - Jetbrains and Source Code Pro  <-- changed the small init to Jetbrains for all fonts.
** note: there's small.init.el on New and in project then there's the init.el in testdir. Differences?
* Looking at packages that are installed but not needed. all-the-icons-dired: when I added
(add-hook 'dired-mode-hook 'all-the-icons-dired-mode)  to init.el I got duplicated icons in a dired buffer. Removed this line.
Deleted some packages that appeard to be not needed. Again, this is on New only.
* Installing rust-analyzer on new fixed server issue -  rustup component add rust-analyzer
* Eglot cant find project on Big. error is eglot  Failed to load workspace.
