* August
* Start times around 3.7 seconds, up from 3. Around 8 seconds for Big.
** New taking 3+ seconds. Big now taking 8 seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
** TODO Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* COMPLETED Played around w/ Yazi flavors.
CLOSED: [2025-08-05 Tue 13:01]
* COMPLETED Reconciled ~/projects/init.el.org with current init.el on new.
CLOSED: [2025-08-06 Wed 10:37]
* TODO Trying to figure out project root.
* TODO Test gh on Big to see if ssh key works there.
* lisp programming.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.
$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject:
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
<<<<<<< HEAD
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
* Yazi is odd. 'r' for rename opens emacs and you change filename there.
** you can't paste into folder, you need to enter the destination folder then paste with 'p' ('P' to overwrite).
** copy is 'y' and cut is 'x'. Trash a file is 'd' after you select the file with <spc> ('D' to delete instead of trash).
** <Return> opens the file so don't that when moving, copying, etc. (also 'O' and <shift-Return>
** <tab> to show file info.
* Have to kill emacs server then start new server before ec will work.
** All terminal apps instantly launch a file in the GUI version of emacs that's already open.
when ec is used:      'emacsclient -n $1'
(that's if M-x server-start has been done and it's a fresh instance of the server.

** Prot emacs runs as GUI on New, as terminal app on Big. Why?
