* November.
* _Start times from ~ 4.7to 5.3 after treemacs on New, up from 4 and 7 for Big, no treemacs._  
* COMPLETED Freeze init.el and work on other things. freezeBIG_06NOV.init.el is latest good b/u.
CLOSED: [2025-10-03 Fri 14:40]* WAITING Prot emacs runs as GUI on New, as terminal app on Big. Why?
** Comparison of Info.plist on New and Big showed no diff.  Both emacs in Applications are 30.2
both brew emacs are /opt/homebrew/bin/emacs BUT menu on New, after pressing f10 is different from menu on Big.
This indcates that something is different.ech
** emacsclient -c does open a new GUI frame.
*** emac in /Applications/ does open faster than starting emacs --daemon then running emacsclient -c. but emacsclient -n $1 opens a file instantly if emacs is open and server is running.
Still not sure why Big opens emacs in terminal while New opens with GUI.
** on Big /opt/homebrew/bin/emacs -q -l ~/project//Prot//init.el opens brew emacs. Not on New.
on new same command opens /Applications//emacs.app n idea why.
* COMPLETED 30OCT - 04NOV. Homogulated init.el on Big and new Broke/fixed Dashboard on New.
CLOSED: [2025-11-06 Thu 10:53]
** Broke Dashboard, couldnt click any items. After a lot of replacing init.el w/ Big init.el finally went back
to previous init.el and that fixed click issue. Now init.el on Big and New NOT synched.
* COMPLETED Need to check init.el.org to see which init.el it matches and if it needs to be modified.
CLOSED: [2025-11-07 Fri 13:26]
* COMPLETED Dired - ls issue.  
CLOSED: [2025-11-07 Fri 13:27]
** macs ls does not support --dired -N; see 'dired-use-ls-dired'
;; lines 98-99 in init.el on New, Big and init.el.org 
(when (string= system-type "darwin")       
  (setq dired-use-ls-dired nil))
*** Seems to work.

* COMPLETED Deleted duplicate org-tag-alist and dashboard-startupify-alist entries on New and Big.
CLOSED: [2025-11-10 Mon 08:14]
intersting that no dupes were found in the init.el.org file - is this a tangling error?
* WAITING Project on Big is not showing all files. Removed entire folder and cloned again. Still not showing.
* Installed Treemacs. Testing.
** treemacs installed ace-window, pfuture, posframe, maybe macrostep?
added:
(use-package treemacs
        :ensure t)
        
*  lisp programming. see backup init.el below.
*** Looking at https://lisp-lang.org/learn/writing-libraries
did some of the examples.. writing files was interesting and useful.
This was done on Big and New, tested, works. Need to do on Plucky and Ducky.
*** lisp is a mess. Tools are installed but need more time getting used to them.
** COMPLETED recommends are SBCL + Slime for compiling and interpeting respectively.

$ curl -o /tmp/ql.lisp http://beta.quicklisp.org/quicklisp.lisp
$ sbcl --no-sysinit --no-userinit --load /tmp/ql.lisp \
       --eval '(quicklisp-quickstart:install :path "~/.quicklisp")' \
       --eval '(ql:add-to-init-file)' \
       --quit

       added quickproject
       (ql:quickload "quicklisp-slime-helper")
       (ql:quickload :quickproject)
       (quiclproject:make-project "test-project")
 
*** COMPLETED Practicals asdf examples are overly complicated and annoying.
CLOSED: [2025-08-05 Tue 07:31]
Practical Lisp and Lisp in a box are at leat 14 years old.
*** COMPLETED Did re-install of Quicklisp on New & Big via: https://www.quicklisp.org/beta/#basic-commands
CLOSED: [2025-08-05 Tue 07:32]
  added dired-x to init.el on New so I can look at elisp via Info
*** COMPLETED asdf is included whan Quicklisp is loaded. Check this on Big and New.
CLOSED: [2025-08-05 Tue 07:33]
*** COMPLETED Removed older lisp tutorials from 'watch later'.
CLOSED: [2025-08-20 Wed 11:33]
*** circle.lisp working after changes. hello.lisp working. array.lisp working but with errors.
+deftest.lisp works with clisp, and with  sbcl when run with sbcl --script.+  block.lisp works after changes. _Dice2.lisp does not work._
fooworld.lisp works. _hellowrld.lisp doesn't work_.    _main.lsip doesn't work_  sequence.lisp runs but throws error: undefined variable X.  Strings.lisp runs as a script.
** Had to re-add quicklisp, quicklisp-slime-helper on Big.
* Rust stuff see Backup init.el below.
** Test rust to see what's actually connecting lsp-wise. Linting, formatting?
*** restarted and tried again and both .py files were linted and completed with pylsp server.
*** added spaces, not tabs and prettify, also tree-sitter integration on New's init.el:

(add-hook 'rust-mode-hook
          (lambda () (setq indent-tabs-mode nil)))

(add-hook 'rust-mode-hook
          (lambda () (prettify-symbols-mode)))

 (use-package rust-mode
  :init
  (setq rust-mode-treesitter-derive t))
*** Rustlings on Big and New but NOT in project folder.
* Backup init.el then choose one language; iisp, rust, python and remove all others.
** Make sure syntax highlighting, completion and marginalia all working with the one language.
** Rinse and repeat for the other two languages.
