
* May
* Start times around 3 seconds.
** New taking 3+ seconds. Big now taking 9+ seconds.
- State "DONE"       from "WAITING"    [2025-04-10 Thu 13:37]
* COMPLETED Script to launch Prot emacs fails on Big. works on New.
CLOSED: [2025-04-24 Thu 08:00]
** Running emacs -q -l ~/project/Prot/init.el in iTerm2 launches GUI Prot emacs.
** Tried making it an actual script, various tweaks.
emacs -q -l ~/project/Prot/init.el
No good. It will open in terminal instead of GUI. Also not loading theme, probably not fonts.
** Problem is only on Big, Works fine GUI on New.
Tried comparing Prot/init.el on Big and New - no differences.
* COMPLETED Tweaks: Going through xah_lee's init.el, alos Prot's and emacs for writers.
CLOSED: [2025-05-06 Tue 12:44]
** DONE added dired-x C-c, C-j is jump to parent dir - opens dired in directory that holds buffer.
CLOSED: [2025-05-06 Tue 12:44]
** DONE added electric parens - if you type ( it adds closing paren automatically)
CLOSED: [2025-05-06 Tue 12:43]
** COMPLETED Put xah_lee.el on New Desktop. Bare bones, works. Simple.
CLOSED: [2025-05-02 Fri 14:32]
** COMPLETED esup -  error'd out the emacs startup profiler.
CLOSED: [2025-05-15 Thu 07:59]
** COMPLETED Couldn't change cursor color using (setq-default cursor-color '"#00FF00")
CLOSED: [2025-05-05 Mon 14:33]
** changed cursor color via M-x change-face --> cursor --> 00FF00 might change cursor type to box.
** Changed cursor type to box and color to IndianRed2.
* COMPLETED Consult is working as intended?
CLOSED: [2025-04-30 Wed 14:36]
For instance: when switching buffers with C-x b Consult shows previews of buffers.

*bold* is *
/italic/ is /
#+begin_emacs-lisp
#+end_emacs-lisp
_underline_ is _
=verbatim= is =
~code~ is ~
+strike-through+ is +
 * NEXT Changed setq to setopt for customizable variables in init.el on Big
** Don't see any downside yet. Will try on New later.
* COMPLETED Updated init.el on Big to match init.el on New.
CLOSED: [2025-05-15 Thu 10:30]
** COMPLETED init.el.org brought up to date to match init.el on New.
CLOSED: [2025-05-09 Fri 08:33]
** init.el.org brought up to date and placed in ~/project.
** +this is now the only template that should be tangled to produce init.el for all machines+*
* COMPLETED Init.el tangled from init.el.org successfully.
CLOSED: [2025-05-02 Fri 08:17]
** Tangled test.el has issues. Do a diff with current init.el to see why.

** Problem was with Org Startup src block. Removing it and recreating it by cut and paste resolved issue.
a couple of other minor issues found in test.el after tangle that were unrelated to babe/tangling.
test.el is now in synch with working init.el on New - which is the primary init.el for now.
** COMPLETED In init.el.org move ;; comments out of src blocks and move to sub headlines.
CLOSED: [2025-05-02 Fri 12:51]
** Moved org fonts, org setup, org roam src blocks out of init.el.org and tangle was 100%
problem exists in those blocks. Need to check them then add one by one.

** slight changes to Prot_Basic.init.el pushed to github.
** updated init.el.org to include changes to New.
* COMPLETED Org Agenda? is just a menu for tasks, notes, journal, etc.
CLOSED: [2025-05-06 Tue 12:45]
** Org tags?
** Org Capture-templates?
** Org-refile
* COMPLETED Projects/org dir created w/ notes, roam, tasks, journal dirs and copy of 3.org
CLOSED: [2025-05-14 Wed 10:06]
** COMPLETED projects/org/3.org is going to be a problem.
CLOSED: [2025-05-12 Mon 14:48]
look into merges in git.
** Easier to just go to a denote format for all notes. Since each note is unique there won't be collisions.
* COMPLETED zshrc - New using oh-my-zsh w/ p10k.
CLOSED: [2025-05-09 Fri 12:28]
** New & Big now using same .zshrc as Plucky plus pyenv and some iterm2 integration, some other items.
alias batcat doesn't work. bat is installed.
*** Big was using oh-my-posh w/o p10k.
*** Plucky was using neither oh-my-posh nor oh-my-zsh.
** Prot init.el working on Big in terminal mode, theme and apps loading but no GUI.
** Prot init.el in project/Prot is now the default aternate init.el if .emacs.d init .el gets corrupted.
* DONE Replacing hard coded paths with $HOME could make init.el transportable.
CLOSED: [2025-05-14 Wed 10:06]
Big doesn't seem to like this. Had to set back to /Users/charles.marano/ 
* COMPLETED Search at point.
CLOSED: [2025-05-16 Fri 11:48]
Words C-s C-w

Characters C-s C-M-y

Whole Lines C-s M-s C-e

To begin a search and replace on the selected words, characters, or sentence M-%
* COMPLETED added consult-denote?
CLOSED: [2025-05-19 Mon 09:44]
git update-index --no-assume-unchanged path/to/file* COMPLETED Big reorg of Project w/ 4 separate git commits from New.
CLOSED: [2025-05-20 Tue 13:30]
* COMPLETED Reconciled init.el.org with New. Big should be the same.
CLOSED: [2025-05-21 Wed 13:56]
** Master copy of init.el.org is now in ~/project/
** tangling init.el.org will produce newtest.el in ~/.emacs.d/
* Doing Zsh Scripting.
** No good intros to zsh programming found so far.
** Debugging:
1. Call the script with the -x option. Example: zsh -x myscript.
2. Modify your scripts header to include -x. Example: #!/bin/zsh -x.
3. Turn on debugging in certain parts of your code. Example: #!/usr/bin/env zsh set - x.
** Completed into pdf: Scripting_Intro_Zsh.pdf
* Lisp programming.
* DONE emacs server / client.
CLOSED: [2025-05-22 Thu 07:42]
** DONE put plist into launch agents folder to start emacs --daemon automatically on restart.
CLOSED: [2025-05-22 Thu 07:45]
*** advantage is should be able to force files to open quickly in emacsclient.
*** emacs start ~3 secs. emacsclient starts in 2.37 secs.
*** emacsclient -n <filename>  <-- reuse frame, seems to work.
*** emacsclient -a '' -c <--satarts daemon and client
*** emacs --daemon   emacs --fg-daemon emacsclient -cache
*** emacsclient --no-wait -r <filename>   <-- should reuse existing frame, doesn't.
*** emacsclient -cn <filename> &  <-- seems to work. For intial frame after emacs --daemon. _<--_
*** emacsclient --no-wait -c <filename> <-- new GUI frame. _<--works_
** Use C-x 5 0 to kill instance. _<-- works_
**  added alias to .zshrc -->   alias ec='emacsclient -n $1' +<-- use this.+


