
* 2025
** 2025-05 May
*** 2025-05-07 Wednesday
*** 2025-05-12 Monday
**** 02:22 PM - Journal                                             :journal:

Moved older init and zshrc to Mystuff/Old... Generally cleaned up.
Made sure paths in init.el on New all pointed to ~/project/org/ (tasks, notes, etc.)
*** 2025-05-13 Tuesday
**** 02:19 PM - Journal                                             :journal:

Set init.el on Big to init.el_Big_slow then modified init,el - replacing at setopt lines with setq (the older form as used by init.el on New).
Startup time went down by 3 seconds.
** 2025-06 June
*** 2025-06-18 Wednesday
**** 08:23 AM - Journal                                             :journal:

Playing around with terminals, KItty, Ghost, Weterm. Don't like weterm's Lua for config.
Kitty seems useable. Ghosty may be nice but title issue on New, Big shows directory as title.
Now I want to decide if Tmux is worth learning or if split panes, tabs, mutiple windows that
terminal apps offer are enough.
** 2025-10 October
*** 2025-10-30 Thursday
**** 09:43 AM - Journal                                             :journa
** 2025-12 December
*** 2025-12-12 Friday
**** 01:37 PM - Journal                                             :journal:
*** 2025-12-17 Wednesday
**** 09:18 AM - Journal                                             :journal:

Trying to remember how to use org-capture journal.
*** 2025-12-18 Thursday
**** Testing org-capture after it broke.
Entered on [2025-12-18 Thu 07:57]
  (setq org-capture-templates
      '(("t" "Todo" entry (file+headline "~/project/org/tasks/tasks.org" "Tasks")
         "* TODO %?\n  %i\n  %a")
        ("j" "Journal" entry (file+olp+datetree "~/project/org/journal/journal.org")
         "* %?\nEntered on %U\n  %i\n  %a")))
* 2026
** 2026-01 January
*** 2026-01-29 Thursday
**** This is a journal entry.
Entered on [2026-01-29 Thu 14:06]
  
  [[file:~/.emacs.d/init.el::variable-pitch-mode 1]]
**** 
Entered on [2026-01-29 Thu 14:08]
  
  [[file:~/project/org/3.org::*C-c c then j for journal (and not C-c j) C-c a does open agenda][C-c c then j for journal (and not C-c j) C-c a does open agenda]]
** 2026-02 February
*** 2026-02-03 Tuesday
**** Tuesday journal entry.
Didn't do much after blowing up init.el on New Yesterday while trying to eliminate compile errors.
Going to leave init.el alone for a while and focus on Org-journal, Org-Roam and Denote.
Entered on [2026-02-03 Tue 12:49]
  
  [[file:~/project/org/3.org::*Focus follows mouse in Terminal: defaults write com.apple.Terminal FocusFollowsMouse -string YES][Focus follows mouse in Terminal: defaults write com.apple.Terminal FocusFollowsMouse -string YES]]
*** 2026-02-04 Wednesday
**** So created a new init.el based on https://whhone.com/emacs-config/#enable-lexical-binding
and it did not cut down loading time or provide aany immediate benefits but did throw eompile errors.
Saved it as ~/project/newtest2.el  and reverted to 02FEB (highly modified init.el Big and init.el.org stil have older 28JAN init.el
Entered on [2026-02-04 Wed 14:03]
  
  [[file:~/project/org/3.org::*Misc.][Misc.]]
